//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.TUUA.CLIENTEWS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:40758/WSDAO/WSAlarmas.asmx")]
        public string CLIENTEWS_WSAlarmas_WSAlarmas {
            get {
                return ((string)(this["CLIENTEWS_WSAlarmas_WSAlarmas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:40758/WSDAO/WSConfiguracion.asmx")]
        public string CLIENTEWS_WSConfiguracion_WSConfiguracion {
            get {
                return ((string)(this["CLIENTEWS_WSConfiguracion_WSConfiguracion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:40758/WSDAO/WSConsultas.asmx")]
        public string CLIENTEWS_WSConsultas_WSConsultas {
            get {
                return ((string)(this["CLIENTEWS_WSConsultas_WSConsultas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:40758/WSDAO/WSError.asmx")]
        public string CLIENTEWS_WSError_WSError {
            get {
                return ((string)(this["CLIENTEWS_WSError_WSError"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:40758/WSDAO/WSRehabilitacion.asmx")]
        public string CLIENTEWS_WSRehabilitacion_WSRehabilitacion {
            get {
                return ((string)(this["CLIENTEWS_WSRehabilitacion_WSRehabilitacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:40758/WSDAO/WSReportes.asmx")]
        public string CLIENTEWS_WSReportes_WSReportes {
            get {
                return ((string)(this["CLIENTEWS_WSReportes_WSReportes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:40758/WSDAO/WSSeguridad.asmx")]
        public string CLIENTEWS_WSSeguridad_WSSeguridad {
            get {
                return ((string)(this["CLIENTEWS_WSSeguridad_WSSeguridad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:40758/WSDAO/WSTurno.asmx")]
        public string CLIENTEWS_WSTurno_WSTurno {
            get {
                return ((string)(this["CLIENTEWS_WSTurno_WSTurno"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:40758/WSDAO/WSOperacion.asmx")]
        public string CLIENTEWS_WSOperacion_WSOperacion {
            get {
                return ((string)(this["CLIENTEWS_WSOperacion_WSOperacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8923/WSDAO/WSAdministracion.asmx")]
        public string CLIENTEWS_WSAdministracion_WSAdministracion {
            get {
                return ((string)(this["CLIENTEWS_WSAdministracion_WSAdministracion"]));
            }
        }
    }
}
