'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
'
Namespace WSInterbank
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsTipoCambioLAPSoap", [Namespace]:="http://extranetib/Lapextdmz/wsTipoCambioLAP")>  _
    Partial Public Class wsTipoCambioLAP
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private fCargaTipoDeCambioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private fCargaTipoDeCambioTodosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UWBS_TUUA.My.MySettings.Default.UWBS_TUUA_WSInterbank_wsTipoCambioLAP
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event fCargaTipoDeCambioCompleted As fCargaTipoDeCambioCompletedEventHandler
        
        '''<remarks/>
        Public Event fCargaTipoDeCambioTodosCompleted As fCargaTipoDeCambioTodosCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://extranetib/Lapextdmz/wsTipoCambioLAP/fCargaTipoDeCambio", RequestNamespace:="http://extranetib/Lapextdmz/wsTipoCambioLAP", ResponseNamespace:="http://extranetib/Lapextdmz/wsTipoCambioLAP", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fCargaTipoDeCambio(ByVal argFlagCompraVenta As String) As Double
            Dim results() As Object = Me.Invoke("fCargaTipoDeCambio", New Object() {argFlagCompraVenta})
            Return CType(results(0),Double)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fCargaTipoDeCambioAsync(ByVal argFlagCompraVenta As String)
            Me.fCargaTipoDeCambioAsync(argFlagCompraVenta, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fCargaTipoDeCambioAsync(ByVal argFlagCompraVenta As String, ByVal userState As Object)
            If (Me.fCargaTipoDeCambioOperationCompleted Is Nothing) Then
                Me.fCargaTipoDeCambioOperationCompleted = AddressOf Me.OnfCargaTipoDeCambioOperationCompleted
            End If
            Me.InvokeAsync("fCargaTipoDeCambio", New Object() {argFlagCompraVenta}, Me.fCargaTipoDeCambioOperationCompleted, userState)
        End Sub
        
        Private Sub OnfCargaTipoDeCambioOperationCompleted(ByVal arg As Object)
            If (Not (Me.fCargaTipoDeCambioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fCargaTipoDeCambioCompleted(Me, New fCargaTipoDeCambioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://extranetib/Lapextdmz/wsTipoCambioLAP/fCargaTipoDeCambioTodos", RequestNamespace:="http://extranetib/Lapextdmz/wsTipoCambioLAP", ResponseNamespace:="http://extranetib/Lapextdmz/wsTipoCambioLAP", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fCargaTipoDeCambioTodos() As String
            Dim results() As Object = Me.Invoke("fCargaTipoDeCambioTodos", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fCargaTipoDeCambioTodosAsync()
            Me.fCargaTipoDeCambioTodosAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fCargaTipoDeCambioTodosAsync(ByVal userState As Object)
            If (Me.fCargaTipoDeCambioTodosOperationCompleted Is Nothing) Then
                Me.fCargaTipoDeCambioTodosOperationCompleted = AddressOf Me.OnfCargaTipoDeCambioTodosOperationCompleted
            End If
            Me.InvokeAsync("fCargaTipoDeCambioTodos", New Object(-1) {}, Me.fCargaTipoDeCambioTodosOperationCompleted, userState)
        End Sub
        
        Private Sub OnfCargaTipoDeCambioTodosOperationCompleted(ByVal arg As Object)
            If (Not (Me.fCargaTipoDeCambioTodosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fCargaTipoDeCambioTodosCompleted(Me, New fCargaTipoDeCambioTodosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub fCargaTipoDeCambioCompletedEventHandler(ByVal sender As Object, ByVal e As fCargaTipoDeCambioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fCargaTipoDeCambioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Double
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Double)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub fCargaTipoDeCambioTodosCompletedEventHandler(ByVal sender As Object, ByVal e As fCargaTipoDeCambioTodosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fCargaTipoDeCambioTodosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
