//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.TUUA.CLIENTEWS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.61.85/WSDAOLAP/WSConsultas.asmx")]
        public string CLIENTEWS_WSConsulta_WSConsultas {
            get {
                return ((string)(this["CLIENTEWS_WSConsulta_WSConsultas"]));
            }
            set {
                this["CLIENTEWS_WSConsulta_WSConsultas"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5078/WSDAO/WSTurno.asmx")]
        public string CLIENTEWS_WSTurno_WSTurno {
            get {
                return ((string)(this["CLIENTEWS_WSTurno_WSTurno"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5078/WSDAO/WSSeguridad.asmx")]
        public string CLIENTEWS_WSSeguridad_WSSeguridad {
            get {
                return ((string)(this["CLIENTEWS_WSSeguridad_WSSeguridad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5078/WSDAO/WSConfiguracion.asmx")]
        public string CLIENTEWS_WSConfiguracion_WSConfiguracion {
            get {
                return ((string)(this["CLIENTEWS_WSConfiguracion_WSConfiguracion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5078/WSDAO/WSError.asmx")]
        public string CLIENTEWS_WSError_WSError {
            get {
                return ((string)(this["CLIENTEWS_WSError_WSError"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5078/WSDAO/WSAdministracion.asmx")]
        public string CLIENTEWS_WSAdministracion_WSAdministracion {
            get {
                return ((string)(this["CLIENTEWS_WSAdministracion_WSAdministracion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5078/WSDAO/WSConsultas.asmx")]
        public string CLIENTEWS_WSConsultas_WSConsultas {
            get {
                return ((string)(this["CLIENTEWS_WSConsultas_WSConsultas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5078/WSDAO/WSOperacion.asmx")]
        public string CLIENTEWS_WSOperacion_WSOperacion {
            get {
                return ((string)(this["CLIENTEWS_WSOperacion_WSOperacion"]));
            }
        }
    }
}
