# Operacion recibe informacion de puertas : programa que permite realizar cambios en algunos parametros de la puerta
import json
from websocket import create_connection
import generico
import configuracionParametros
import mysql.connector
import logging
import sys
import os
import datetime
import time

str_nombre_puerta = configuracionParametros.NombrePuerta()
dia=datetime.datetime.utcnow() + datetime.timedelta(hours=configuracionParametros.desfazeUTC())
nombre_log = 'traza_ORIP_' + str(datetime.date(year=dia.year,month=dia.month,day=dia.day)) +'.log'
logging.basicConfig(filename=nombre_log,level=logging.DEBUG)
logging.warning("Inicio LAP_SP_ORIP :"+ str(dia))
logging.info(str(dia) + " Conectado LAP_SP_ORIP")

try:
	variable = os.listdir(os.getcwd())
	flag = 0
	for var in variable :
		if(var == 'parametros.txt'):
			flag = flag + 1

	if (flag==0):
		f= open("parametros.txt","w+")
		f.write("COMENTARIO: Escoje el tipo de separador el cual estara entre los datos->(#)  No cambiar el orden de los parametros\n")
		f.write("1 web service verificar red:	#https://ec3ae29e.ngrok.io/api/TuuaAccesos/getstatus#\n")
		f.write("2 web service registrar trama:	#https://ec3ae29e.ngrok.io/api/TuuaAccesos/PostRegistrarTrama#\n")
		f.write("3 web service registro contin:	#https://ec3ae29e.ngrok.io/api/TuuaAccesos/PostRegistrarTramaContingencia#\n")
		f.write("4 web service estado puerta:	#https://ec3ae29e.ngrok.io/api/TuuaAccesos/GetMolinetePorCodigo?cod_molinete=#\n")
		f.write("5 web service llaves destrabe:	#https://ec3ae29e.ngrok.io/api/TuuaAccesos/GetLlavesDestrabe#\n")
		f.write("6 Timeout verficar red:		#1#\n")
		f.write("7 Timeout registrar trama:	#1#\n")
		f.write("8 Timeout registro contin:	#1#\n")
		f.write("9 Timeout estado puerta:	#1#\n")
		f.write("10 Timeout llaves de destrabe:	#1#\n")
		f.write("11 Horas antes:			#12#\n")
		f.write("12 Horas despues:		#12#\n")
		f.write("13 Borrado base de datos:	#30#\n")
		f.write("14 Borrado log:			#10#\n")
		f.write("15 Hora de borrado:		#13:06#\n")
		f.write("16 Datos base de datos:		#localhost,root,root,lap#\n")
		f.write("17 Aeropuerto origen:		#LIM#\n")
		f.write("18 Nombre puerta:		#L03#\n")
		f.write("19 ip scanner:			#192.168.88.252#\n")
		f.write("20 puerto scanner:		#65432#\n")
		f.write("21 direccion controlador:	#http://192.168.0.200:8081/#\n")
		f.write("22 gateway computador:		#192.168.0.50#\n")
		f.write("23 estado cerrado puerta:	#L#\n")
		f.write("24 estado abierto puerta:	#O#\n")
		f.write("25 estado normal puerta:	#E#\n")
		f.write("26 rango de muestreo:		#40#\n")
		f.write("27 duracion de muestreo:	#0.5#\n")
		f.write("28 status query:		#SQ#\n")
		f.write("29 autorizar pase:		#CC#\n")
		f.write("30 intento de fraude:		#CR#\n")
		f.write("31 Completo pase:		#QBOK#\n")
		f.write("32 regreso:			#CNXB#\n")
		f.write("33 incompleto pase:		#TODT#\n")
		f.write("34 bloqueo:			#FRXO#\n")
		f.write("35 paso incorrecto:		#FR2X#\n")
		f.write("36 emergencia:			#EXOK#\n")
		f.close()

except Exception as e:
	logging.error(str(datetime.datetime.utcnow() + datetime.timedelta(hours=configuracionParametros.desfazeUTC())) + " Error en LAP_SP_ORIP en linea :     " + str(sys.exc_info()[2].tb_lineno)  + "     " + str(e.args),exc_info=True)
except :
	logging.error(str(datetime.datetime.utcnow() + datetime.timedelta(hours=configuracionParametros.desfazeUTC())) + " Error en LAP_SP_ORIP en linea :     " + str(sys.exc_info()[2].tb_lineno)  + "      Error mayor",exc_info=True)

try:
	BD = configuracionParametros.datosBD()
	mydb = mysql.connector.connect(
		host=BD[0],
		user=BD[1],
		passwd=BD[2],
		database=BD[3],
	)
	my_cursor = mydb.cursor()
	my_cursor.execute("SELECT * FROM LAP_SP_estado_de_puerta WHERE  dsc_puerta = '"+ configuracionParametros.NombrePuerta()+"' ")
	results = my_cursor.fetchall()

	borradoBD = 30
	borradoLog = 10
	NombrePuerta = "L03"

	msg ={
	  "data": {
	    "borradoBD": borradoBD,
	    "borradoLog": borradoLog,
	    "nombrePuerta": NombrePuerta,
	  },
	}
	y = json.dumps(msg)
	ws = create_connection("ws://echo.websocket.org/")
	print("Sending 'Hello, World'...")
	ws.send(y)
	print("Sent")
	print("Receiving...")
	result =  ws.recv()
	print("Received '%s'" % result)
	ws.close()

	datos = ((result.split('{'))[2].split('}'))[0].split(',')
	i=0
	lista=[]
	for ejem in datos:
		temporal = ejem.split('"')
		temporal2 = ejem.split(':')

		lista.append(temporal[1])
		lista.append(temporal2[1].replace(' ','',1))

		f = open("parametros.txt","r")
		if f.mode == "r":
			contents = f.read()
			partes = contents.split('\n')
		f.close

		if (temporal[1] == 'webLAP'):

			os.remove("parametros.txt")
			temp = partes[1].split('#')
			cadena = temp[0]+'#'+ temporal2[1].replace(' ','',1) +'#'+'\n'
			f= open("parametros.txt","w+")
			f.write(partes[0]+"\n")
			f.write(cadena)
			f.write(partes[2]+"\n")
			f.write(partes[3]+"\n")
			f.write(partes[4]+"\n")
			f.write(partes[5]+"\n")
			f.write(partes[6]+"\n")
			f.write(partes[7]+"\n")
			f.write(partes[8]+"\n")
			f.write(partes[9]+"\n")
			f.write(partes[10]+"\n")
			f.write(partes[11]+"\n")
			f.write(partes[12]+"\n")
			f.write(partes[13]+"\n")
			f.write(partes[14]+"\n")
			f.write(partes[15]+"\n")
			f.write(partes[16]+"\n")
			f.write(partes[17]+"\n")
			f.write(partes[18]+"\n")
			f.write(partes[19]+"\n")
			f.write(partes[20]+"\n")
			f.write(partes[21]+"\n")
			f.write(partes[22]+"\n")
			f.write(partes[23]+"\n")
			f.write(partes[24]+"\n")
			f.write(partes[25]+"\n")
			f.write(partes[26]+"\n")
			f.write(partes[27]+"\n")
			f.write(partes[28]+"\n")
			f.write(partes[29]+"\n")
			f.write(partes[30]+"\n")
			f.write(partes[31]+"\n")
			f.write(partes[32]+"\n")
			f.write(partes[33]+"\n")
			f.write(partes[34]+"\n")
			f.write(partes[35])
			f.close()

		elif (temporal[1] == 'timeout'):
			os.remove("parametros.txt")
			temp = partes[2].split('#')
			cadena = temp[0]+'#'+ temporal2[1].replace(' ','',1) +'#' + '\n'
			f= open("parametros.txt","w+")
			f.write(partes[0]+"\n")
			f.write(partes[1]+"\n")
			f.write(cadena)
			f.write(partes[3]+"\n")
			f.write(partes[4]+"\n")
			f.write(partes[5]+"\n")
			f.write(partes[6]+"\n")
			f.write(partes[7]+"\n")
			f.write(partes[8]+"\n")
			f.write(partes[9]+"\n")
			f.write(partes[10]+"\n")
			f.write(partes[11]+"\n")
			f.write(partes[12]+"\n")
			f.write(partes[13]+"\n")
			f.write(partes[14]+"\n")
			f.write(partes[15]+"\n")
			f.write(partes[16]+"\n")
			f.write(partes[17]+"\n")
			f.write(partes[18]+"\n")
			f.write(partes[19]+"\n")
			f.write(partes[20]+"\n")
			f.write(partes[21]+"\n")
			f.write(partes[22]+"\n")
			f.write(partes[23]+"\n")
			f.write(partes[24]+"\n")
			f.write(partes[25]+"\n")
			f.write(partes[26]+"\n")
			f.write(partes[27]+"\n")
			f.write(partes[28]+"\n")
			f.write(partes[29]+"\n")
			f.write(partes[30]+"\n")
			f.write(partes[31]+"\n")
			f.write(partes[32]+"\n")
			f.write(partes[33]+"\n")
			f.write(partes[34]+"\n")
			f.write(partes[35])
			f.close()

		elif (temporal[1] == 'horaTem'):
			os.remove("parametros.txt")
			temp = partes[3].split('#')
			cadena = temp[0]+'#'+ temporal2[1].replace(' ','',1) +'#'+ '\n'
			f= open("parametros.txt","w+")
			f.write(partes[0]+"\n")
			f.write(partes[1]+"\n")
			f.write(partes[2]+"\n")
			f.write(cadena)
			f.write(partes[4]+"\n")
			f.write(partes[5]+"\n")
			f.write(partes[6]+"\n")
			f.write(partes[7]+"\n")
			f.write(partes[8]+"\n")
			f.write(partes[9]+"\n")
			f.write(partes[10]+"\n")
			f.write(partes[11]+"\n")
			f.write(partes[12]+"\n")
			f.write(partes[13]+"\n")
			f.write(partes[14]+"\n")
			f.write(partes[15]+"\n")
			f.write(partes[16]+"\n")
			f.write(partes[17]+"\n")
			f.write(partes[18]+"\n")
			f.write(partes[19]+"\n")
			f.write(partes[20]+"\n")
			f.write(partes[21]+"\n")
			f.write(partes[22]+"\n")
			f.write(partes[23]+"\n")
			f.write(partes[24]+"\n")
			f.write(partes[25]+"\n")
			f.write(partes[26]+"\n")
			f.write(partes[27]+"\n")
			f.write(partes[28]+"\n")
			f.write(partes[29]+"\n")
			f.write(partes[30]+"\n")
			f.write(partes[31]+"\n")
			f.write(partes[32]+"\n")
			f.write(partes[33]+"\n")
			f.write(partes[34]+"\n")
			f.write(partes[35])
			f.close()

		elif (temporal[1] == 'horaTar'):
			os.remove("parametros.txt")
			temp = partes[4].split('#')
			cadena = temp[0]+'#'+ temporal2[1].replace(' ','',1) +'#' + '\n'
			f= open("parametros.txt","w+")
			f.write(partes[0]+"\n")
			f.write(partes[1]+"\n")
			f.write(partes[2]+"\n")
			f.write(partes[3]+"\n")
			f.write(cadena)
			f.write(partes[5]+"\n")
			f.write(partes[6]+"\n")
			f.write(partes[7]+"\n")
			f.write(partes[8]+"\n")
			f.write(partes[9]+"\n")
			f.write(partes[10]+"\n")
			f.write(partes[11]+"\n")
			f.write(partes[12]+"\n")
			f.write(partes[13]+"\n")
			f.write(partes[14]+"\n")
			f.write(partes[15]+"\n")
			f.write(partes[16]+"\n")
			f.write(partes[17]+"\n")
			f.write(partes[18]+"\n")
			f.write(partes[19]+"\n")
			f.write(partes[20]+"\n")
			f.write(partes[21]+"\n")
			f.write(partes[22]+"\n")
			f.write(partes[23]+"\n")
			f.write(partes[24]+"\n")
			f.write(partes[25]+"\n")
			f.write(partes[26]+"\n")
			f.write(partes[27]+"\n")
			f.write(partes[28]+"\n")
			f.write(partes[29]+"\n")
			f.write(partes[30]+"\n")
			f.write(partes[31]+"\n")
			f.write(partes[32]+"\n")
			f.write(partes[33]+"\n")
			f.write(partes[34]+"\n")
			f.write(partes[35])
			f.close()

		elif (temporal[1] == 'borradoBD'):
			os.remove("parametros.txt")
			temp = partes[5].split('#')
			cadena = temp[0]+'#'+ temporal2[1].replace(' ','',1) +'#' + '\n'
			f= open("parametros.txt","w+")
			f.write(partes[0]+"\n")
			f.write(partes[1]+"\n")
			f.write(partes[2]+"\n")
			f.write(partes[3]+"\n")
			f.write(partes[4]+"\n")
			f.write(cadena)
			f.write(partes[6]+"\n")
			f.write(partes[7]+"\n")
			f.write(partes[8]+"\n")
			f.write(partes[9]+"\n")
			f.write(partes[10]+"\n")
			f.write(partes[11]+"\n")
			f.write(partes[12]+"\n")
			f.write(partes[13]+"\n")
			f.write(partes[14]+"\n")
			f.write(partes[15]+"\n")
			f.write(partes[16]+"\n")
			f.write(partes[17]+"\n")
			f.write(partes[18]+"\n")
			f.write(partes[19]+"\n")
			f.write(partes[20]+"\n")
			f.write(partes[21]+"\n")
			f.write(partes[22]+"\n")
			f.write(partes[23]+"\n")
			f.write(partes[24]+"\n")
			f.write(partes[25]+"\n")
			f.write(partes[26]+"\n")
			f.write(partes[27]+"\n")
			f.write(partes[28]+"\n")
			f.write(partes[29]+"\n")
			f.write(partes[30]+"\n")
			f.write(partes[31]+"\n")
			f.write(partes[32]+"\n")
			f.write(partes[33]+"\n")
			f.write(partes[34]+"\n")
			f.write(partes[35])
			f.close()

		elif (temporal[1] == 'borradoLog'):
			os.remove("parametros.txt")
			temp = partes[6].split('#')
			cadena = temp[0]+'#'+ temporal2[1].replace(' ','',1) +'#' + '\n'
			f= open("parametros.txt","w+")
			f.write(partes[0]+"\n")
			f.write(partes[1]+"\n")
			f.write(partes[2]+"\n")
			f.write(partes[3]+"\n")
			f.write(partes[4]+"\n")
			f.write(partes[5]+"\n")
			f.write(cadena)
			f.write(partes[7]+"\n")
			f.write(partes[8]+"\n")
			f.write(partes[9]+"\n")
			f.write(partes[10]+"\n")
			f.write(partes[11]+"\n")
			f.write(partes[12]+"\n")
			f.write(partes[13]+"\n")
			f.write(partes[14]+"\n")
			f.write(partes[15]+"\n")
			f.write(partes[16]+"\n")
			f.write(partes[17]+"\n")
			f.write(partes[18]+"\n")
			f.write(partes[19]+"\n")
			f.write(partes[20]+"\n")
			f.write(partes[21]+"\n")
			f.write(partes[22]+"\n")
			f.write(partes[23]+"\n")
			f.write(partes[24]+"\n")
			f.write(partes[25]+"\n")
			f.write(partes[26]+"\n")
			f.write(partes[27]+"\n")
			f.write(partes[28]+"\n")
			f.write(partes[29]+"\n")
			f.write(partes[30]+"\n")
			f.write(partes[31]+"\n")
			f.write(partes[32]+"\n")
			f.write(partes[33]+"\n")
			f.write(partes[34]+"\n")
			f.write(partes[35])
			f.close()

		elif (temporal[1] == 'horaBorr'):
			os.remove("parametros.txt")
			temp = partes[7].split('#')
			cadena = temp[0]+'#'+ temporal2[1].replace(' ','',1) +'#' + '\n'
			f= open("parametros.txt","w+")
			f.write(partes[0]+"\n")
			f.write(partes[1]+"\n")
			f.write(partes[2]+"\n")
			f.write(partes[3]+"\n")
			f.write(partes[4]+"\n")
			f.write(partes[5]+"\n")
			f.write(partes[6]+"\n")
			f.write(cadena)
			f.write(partes[8]+"\n")
			f.write(partes[9]+"\n")
			f.write(partes[10]+"\n")
			f.write(partes[11]+"\n")
			f.write(partes[12]+"\n")
			f.write(partes[13]+"\n")
			f.write(partes[14]+"\n")
			f.write(partes[15]+"\n")
			f.write(partes[16]+"\n")
			f.write(partes[17]+"\n")
			f.write(partes[18]+"\n")
			f.write(partes[19]+"\n")
			f.write(partes[20]+"\n")
			f.write(partes[21]+"\n")
			f.write(partes[22]+"\n")
			f.write(partes[23]+"\n")
			f.write(partes[24]+"\n")
			f.write(partes[25]+"\n")
			f.write(partes[26]+"\n")
			f.write(partes[27]+"\n")
			f.write(partes[28]+"\n")
			f.write(partes[29]+"\n")
			f.write(partes[30]+"\n")
			f.write(partes[31]+"\n")
			f.write(partes[32]+"\n")
			f.write(partes[33]+"\n")
			f.write(partes[34]+"\n")
			f.write(partes[35])
			f.close()

		elif (temporal[1] == 'datosBD'):
			os.remove("parametros.txt")
			temp = partes[8].split('#')
			cadena = temp[0]+'#'+ temporal2[1].replace(' ','',1) +'#' + '\n'
			f= open("parametros.txt","w+")
			f.write(partes[0]+"\n")
			f.write(partes[1]+"\n")
			f.write(partes[2]+"\n")
			f.write(partes[3]+"\n")
			f.write(partes[4]+"\n")
			f.write(partes[5]+"\n")
			f.write(partes[6]+"\n")
			f.write(partes[7]+"\n")
			f.write(cadena)
			f.write(partes[9]+"\n")
			f.write(partes[10]+"\n")
			f.write(partes[11]+"\n")
			f.write(partes[12]+"\n")
			f.write(partes[13]+"\n")
			f.write(partes[14]+"\n")
			f.write(partes[15]+"\n")
			f.write(partes[16]+"\n")
			f.write(partes[17]+"\n")
			f.write(partes[18]+"\n")
			f.write(partes[19]+"\n")
			f.write(partes[20]+"\n")
			f.write(partes[21]+"\n")
			f.write(partes[22]+"\n")
			f.write(partes[23]+"\n")
			f.write(partes[24]+"\n")
			f.write(partes[25]+"\n")
			f.write(partes[26]+"\n")
			f.write(partes[27]+"\n")
			f.write(partes[28]+"\n")
			f.write(partes[29]+"\n")
			f.write(partes[30]+"\n")
			f.write(partes[31]+"\n")
			f.write(partes[32]+"\n")
			f.write(partes[33]+"\n")
			f.write(partes[34]+"\n")
			f.write(partes[35])
			f.close()

		elif (temporal[1] == 'aerOri'):
			os.remove("parametros.txt")
			temp = partes[9].split('#')
			cadena = temp[0]+'#'+ temporal2[1].replace(' ','',1) +'#' + '\n'
			f= open("parametros.txt","w+")
			f.write(partes[0]+"\n")
			f.write(partes[1]+"\n")
			f.write(partes[2]+"\n")
			f.write(partes[3]+"\n")
			f.write(partes[4]+"\n")
			f.write(partes[5]+"\n")
			f.write(partes[6]+"\n")
			f.write(partes[7]+"\n")
			f.write(partes[8]+"\n")
			f.write(cadena)
			f.write(partes[10]+"\n")
			f.write(partes[11]+"\n")
			f.write(partes[12]+"\n")
			f.write(partes[13]+"\n")
			f.write(partes[14]+"\n")
			f.write(partes[15]+"\n")
			f.write(partes[16]+"\n")
			f.write(partes[17]+"\n")
			f.write(partes[18]+"\n")
			f.write(partes[19]+"\n")
			f.write(partes[20]+"\n")
			f.write(partes[21]+"\n")
			f.write(partes[22]+"\n")
			f.write(partes[23]+"\n")
			f.write(partes[24]+"\n")
			f.write(partes[25]+"\n")
			f.write(partes[26]+"\n")
			f.write(partes[27]+"\n")
			f.write(partes[28]+"\n")
			f.write(partes[29]+"\n")
			f.write(partes[30]+"\n")
			f.write(partes[31]+"\n")
			f.write(partes[32]+"\n")
			f.write(partes[33]+"\n")
			f.write(partes[34]+"\n")
			f.write(partes[35])
			f.close()

		elif (temporal[1] == 'nombrePuerta'):
			os.remove("parametros.txt")
			temp = partes[10].split('#')
			cadena = temp[0]+'#'+ temporal2[1].replace(' ','',1) +'#' + '\n'
			f= open("parametros.txt","w+")
			f.write(partes[0]+"\n")
			f.write(partes[1]+"\n")
			f.write(partes[2]+"\n")
			f.write(partes[3]+"\n")
			f.write(partes[4]+"\n")
			f.write(partes[5]+"\n")
			f.write(partes[6]+"\n")
			f.write(partes[7]+"\n")
			f.write(partes[8]+"\n")
			f.write(partes[9]+"\n")
			f.write(cadena)
			f.write(partes[11]+"\n")
			f.write(partes[12]+"\n")
			f.write(partes[13]+"\n")
			f.write(partes[14]+"\n")
			f.write(partes[15]+"\n")
			f.write(partes[16]+"\n")
			f.write(partes[17]+"\n")
			f.write(partes[18]+"\n")
			f.write(partes[19]+"\n")
			f.write(partes[20]+"\n")
			f.write(partes[21]+"\n")
			f.write(partes[22]+"\n")
			f.write(partes[23]+"\n")
			f.write(partes[24]+"\n")
			f.write(partes[25]+"\n")
			f.write(partes[26]+"\n")
			f.write(partes[27]+"\n")
			f.write(partes[28]+"\n")
			f.write(partes[29]+"\n")
			f.write(partes[30]+"\n")
			f.write(partes[31]+"\n")
			f.write(partes[32]+"\n")
			f.write(partes[33]+"\n")
			f.write(partes[34]+"\n")
			f.write(partes[35])
			f.close()

	print(lista)
	
except Exception as e:
	#print("algo malo")
	logging.error( str(generico.diahora()) + " Error en LAP_SP_ORIP en linea :     " + str(sys.exc_info()[2].tb_lineno)  + "     " + str(e.args),exc_info=True)
except:
	#print("algo malo")
	logging.error( str(generico.diahora()) + " Error en LAP_SP_ORIP en linea :     " + str(sys.exc_info()[2].tb_lineno)  + "      Error mayor"+str(sys.exc_info()[0]),exc_info=True)

time.sleep(2)