//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace LAP.TUUA.CLIENTEWS.WSTurno {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSTurnoSoap", Namespace="http://tempuri.org/")]
    public partial class WSTurno : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback autenticarOperationCompleted;
        
        private System.Threading.SendOrPostCallback crearTurnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarTurnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerTurnoIniciadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarTurnoMontoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarTurnoMontoOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificarTurnoCerradoxUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificarTurnoCerradoxPtoVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarMonedasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTurnoMontosPorTurnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTasaCambioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSTurno() {
            this.Url = global::LAP.TUUA.CLIENTEWS.Properties.Settings.Default.CLIENTEWS_WSTurno_WSTurno;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event autenticarCompletedEventHandler autenticarCompleted;
        
        /// <remarks/>
        public event crearTurnoCompletedEventHandler crearTurnoCompleted;
        
        /// <remarks/>
        public event ActualizarTurnoCompletedEventHandler ActualizarTurnoCompleted;
        
        /// <remarks/>
        public event obtenerTurnoIniciadoCompletedEventHandler obtenerTurnoIniciadoCompleted;
        
        /// <remarks/>
        public event registrarTurnoMontoCompletedEventHandler registrarTurnoMontoCompleted;
        
        /// <remarks/>
        public event ActualizarTurnoMontoCompletedEventHandler ActualizarTurnoMontoCompleted;
        
        /// <remarks/>
        public event verificarTurnoCerradoxUsuarioCompletedEventHandler verificarTurnoCerradoxUsuarioCompleted;
        
        /// <remarks/>
        public event verificarTurnoCerradoxPtoVentaCompletedEventHandler verificarTurnoCerradoxPtoVentaCompleted;
        
        /// <remarks/>
        public event ListarMonedasCompletedEventHandler ListarMonedasCompleted;
        
        /// <remarks/>
        public event ListarTurnoMontosPorTurnoCompletedEventHandler ListarTurnoMontosPorTurnoCompleted;
        
        /// <remarks/>
        public event ListarTasaCambioCompletedEventHandler ListarTasaCambioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/autenticar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario autenticar(string sCuenta, string sClave) {
            object[] results = this.Invoke("autenticar", new object[] {
                        sCuenta,
                        sClave});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void autenticarAsync(string sCuenta, string sClave) {
            this.autenticarAsync(sCuenta, sClave, null);
        }
        
        /// <remarks/>
        public void autenticarAsync(string sCuenta, string sClave, object userState) {
            if ((this.autenticarOperationCompleted == null)) {
                this.autenticarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnautenticarOperationCompleted);
            }
            this.InvokeAsync("autenticar", new object[] {
                        sCuenta,
                        sClave}, this.autenticarOperationCompleted, userState);
        }
        
        private void OnautenticarOperationCompleted(object arg) {
            if ((this.autenticarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.autenticarCompleted(this, new autenticarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearTurno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool crearTurno(string as_cod_secuencial, string as_cod_usuario, string as_cod_equipo, ref string strTurnoError) {
            object[] results = this.Invoke("crearTurno", new object[] {
                        as_cod_secuencial,
                        as_cod_usuario,
                        as_cod_equipo,
                        strTurnoError});
            strTurnoError = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void crearTurnoAsync(string as_cod_secuencial, string as_cod_usuario, string as_cod_equipo, string strTurnoError) {
            this.crearTurnoAsync(as_cod_secuencial, as_cod_usuario, as_cod_equipo, strTurnoError, null);
        }
        
        /// <remarks/>
        public void crearTurnoAsync(string as_cod_secuencial, string as_cod_usuario, string as_cod_equipo, string strTurnoError, object userState) {
            if ((this.crearTurnoOperationCompleted == null)) {
                this.crearTurnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearTurnoOperationCompleted);
            }
            this.InvokeAsync("crearTurno", new object[] {
                        as_cod_secuencial,
                        as_cod_usuario,
                        as_cod_equipo,
                        strTurnoError}, this.crearTurnoOperationCompleted, userState);
        }
        
        private void OncrearTurnoOperationCompleted(object arg) {
            if ((this.crearTurnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearTurnoCompleted(this, new crearTurnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarTurno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarTurno(Turno objTurno) {
            object[] results = this.Invoke("ActualizarTurno", new object[] {
                        objTurno});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarTurnoAsync(Turno objTurno) {
            this.ActualizarTurnoAsync(objTurno, null);
        }
        
        /// <remarks/>
        public void ActualizarTurnoAsync(Turno objTurno, object userState) {
            if ((this.ActualizarTurnoOperationCompleted == null)) {
                this.ActualizarTurnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarTurnoOperationCompleted);
            }
            this.InvokeAsync("ActualizarTurno", new object[] {
                        objTurno}, this.ActualizarTurnoOperationCompleted, userState);
        }
        
        private void OnActualizarTurnoOperationCompleted(object arg) {
            if ((this.ActualizarTurnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarTurnoCompleted(this, new ActualizarTurnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerTurnoIniciado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Turno obtenerTurnoIniciado(string as_usuario) {
            object[] results = this.Invoke("obtenerTurnoIniciado", new object[] {
                        as_usuario});
            return ((Turno)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerTurnoIniciadoAsync(string as_usuario) {
            this.obtenerTurnoIniciadoAsync(as_usuario, null);
        }
        
        /// <remarks/>
        public void obtenerTurnoIniciadoAsync(string as_usuario, object userState) {
            if ((this.obtenerTurnoIniciadoOperationCompleted == null)) {
                this.obtenerTurnoIniciadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerTurnoIniciadoOperationCompleted);
            }
            this.InvokeAsync("obtenerTurnoIniciado", new object[] {
                        as_usuario}, this.obtenerTurnoIniciadoOperationCompleted, userState);
        }
        
        private void OnobtenerTurnoIniciadoOperationCompleted(object arg) {
            if ((this.obtenerTurnoIniciadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerTurnoIniciadoCompleted(this, new obtenerTurnoIniciadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarTurnoMonto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool registrarTurnoMonto(TurnoMonto[] listaMontos) {
            object[] results = this.Invoke("registrarTurnoMonto", new object[] {
                        listaMontos});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void registrarTurnoMontoAsync(TurnoMonto[] listaMontos) {
            this.registrarTurnoMontoAsync(listaMontos, null);
        }
        
        /// <remarks/>
        public void registrarTurnoMontoAsync(TurnoMonto[] listaMontos, object userState) {
            if ((this.registrarTurnoMontoOperationCompleted == null)) {
                this.registrarTurnoMontoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarTurnoMontoOperationCompleted);
            }
            this.InvokeAsync("registrarTurnoMonto", new object[] {
                        listaMontos}, this.registrarTurnoMontoOperationCompleted, userState);
        }
        
        private void OnregistrarTurnoMontoOperationCompleted(object arg) {
            if ((this.registrarTurnoMontoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarTurnoMontoCompleted(this, new registrarTurnoMontoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarTurnoMonto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarTurnoMonto(TurnoMonto[] listaMontos) {
            object[] results = this.Invoke("ActualizarTurnoMonto", new object[] {
                        listaMontos});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarTurnoMontoAsync(TurnoMonto[] listaMontos) {
            this.ActualizarTurnoMontoAsync(listaMontos, null);
        }
        
        /// <remarks/>
        public void ActualizarTurnoMontoAsync(TurnoMonto[] listaMontos, object userState) {
            if ((this.ActualizarTurnoMontoOperationCompleted == null)) {
                this.ActualizarTurnoMontoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarTurnoMontoOperationCompleted);
            }
            this.InvokeAsync("ActualizarTurnoMonto", new object[] {
                        listaMontos}, this.ActualizarTurnoMontoOperationCompleted, userState);
        }
        
        private void OnActualizarTurnoMontoOperationCompleted(object arg) {
            if ((this.ActualizarTurnoMontoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarTurnoMontoCompleted(this, new ActualizarTurnoMontoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verificarTurnoCerradoxUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verificarTurnoCerradoxUsuario(string as_usuario) {
            object[] results = this.Invoke("verificarTurnoCerradoxUsuario", new object[] {
                        as_usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verificarTurnoCerradoxUsuarioAsync(string as_usuario) {
            this.verificarTurnoCerradoxUsuarioAsync(as_usuario, null);
        }
        
        /// <remarks/>
        public void verificarTurnoCerradoxUsuarioAsync(string as_usuario, object userState) {
            if ((this.verificarTurnoCerradoxUsuarioOperationCompleted == null)) {
                this.verificarTurnoCerradoxUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificarTurnoCerradoxUsuarioOperationCompleted);
            }
            this.InvokeAsync("verificarTurnoCerradoxUsuario", new object[] {
                        as_usuario}, this.verificarTurnoCerradoxUsuarioOperationCompleted, userState);
        }
        
        private void OnverificarTurnoCerradoxUsuarioOperationCompleted(object arg) {
            if ((this.verificarTurnoCerradoxUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificarTurnoCerradoxUsuarioCompleted(this, new verificarTurnoCerradoxUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verificarTurnoCerradoxPtoVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verificarTurnoCerradoxPtoVenta(string as_ptoventa) {
            object[] results = this.Invoke("verificarTurnoCerradoxPtoVenta", new object[] {
                        as_ptoventa});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verificarTurnoCerradoxPtoVentaAsync(string as_ptoventa) {
            this.verificarTurnoCerradoxPtoVentaAsync(as_ptoventa, null);
        }
        
        /// <remarks/>
        public void verificarTurnoCerradoxPtoVentaAsync(string as_ptoventa, object userState) {
            if ((this.verificarTurnoCerradoxPtoVentaOperationCompleted == null)) {
                this.verificarTurnoCerradoxPtoVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificarTurnoCerradoxPtoVentaOperationCompleted);
            }
            this.InvokeAsync("verificarTurnoCerradoxPtoVenta", new object[] {
                        as_ptoventa}, this.verificarTurnoCerradoxPtoVentaOperationCompleted, userState);
        }
        
        private void OnverificarTurnoCerradoxPtoVentaOperationCompleted(object arg) {
            if ((this.verificarTurnoCerradoxPtoVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificarTurnoCerradoxPtoVentaCompleted(this, new verificarTurnoCerradoxPtoVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarMonedas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Moneda[] ListarMonedas() {
            object[] results = this.Invoke("ListarMonedas", new object[0]);
            return ((Moneda[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarMonedasAsync() {
            this.ListarMonedasAsync(null);
        }
        
        /// <remarks/>
        public void ListarMonedasAsync(object userState) {
            if ((this.ListarMonedasOperationCompleted == null)) {
                this.ListarMonedasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarMonedasOperationCompleted);
            }
            this.InvokeAsync("ListarMonedas", new object[0], this.ListarMonedasOperationCompleted, userState);
        }
        
        private void OnListarMonedasOperationCompleted(object arg) {
            if ((this.ListarMonedasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarMonedasCompleted(this, new ListarMonedasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarTurnoMontosPorTurno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TurnoMonto[] ListarTurnoMontosPorTurno(string scodturno) {
            object[] results = this.Invoke("ListarTurnoMontosPorTurno", new object[] {
                        scodturno});
            return ((TurnoMonto[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTurnoMontosPorTurnoAsync(string scodturno) {
            this.ListarTurnoMontosPorTurnoAsync(scodturno, null);
        }
        
        /// <remarks/>
        public void ListarTurnoMontosPorTurnoAsync(string scodturno, object userState) {
            if ((this.ListarTurnoMontosPorTurnoOperationCompleted == null)) {
                this.ListarTurnoMontosPorTurnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTurnoMontosPorTurnoOperationCompleted);
            }
            this.InvokeAsync("ListarTurnoMontosPorTurno", new object[] {
                        scodturno}, this.ListarTurnoMontosPorTurnoOperationCompleted, userState);
        }
        
        private void OnListarTurnoMontosPorTurnoOperationCompleted(object arg) {
            if ((this.ListarTurnoMontosPorTurnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTurnoMontosPorTurnoCompleted(this, new ListarTurnoMontosPorTurnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarTasaCambio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ListarTasaCambio() {
            object[] results = this.Invoke("ListarTasaCambio", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ListarTasaCambioAsync() {
            this.ListarTasaCambioAsync(null);
        }
        
        /// <remarks/>
        public void ListarTasaCambioAsync(object userState) {
            if ((this.ListarTasaCambioOperationCompleted == null)) {
                this.ListarTasaCambioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTasaCambioOperationCompleted);
            }
            this.InvokeAsync("ListarTasaCambio", new object[0], this.ListarTasaCambioOperationCompleted, userState);
        }
        
        private void OnListarTasaCambioOperationCompleted(object arg) {
            if ((this.ListarTasaCambioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTasaCambioCompleted(this, new ListarTasaCambioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private string sCodUsuarioField;
        
        private string sNomUsuarioField;
        
        private string sApeUsuarioField;
        
        private string sCtaUsuarioField;
        
        private string sPwdActualUsuarioField;
        
        private string sFlgCambioClaveField;
        
        private string sTipoEstadoActualField;
        
        private System.DateTime dtFchVigenciaField;
        
        private string sTipoGrupoField;
        
        private string sDscEstadoActualField;
        
        private string sDscGrupoField;
        
        private string sFchCreacionField;
        
        private string sHoraCreacionField;
        
        private string sCodUsuarioCreacionField;
        
        private string sLogUsuarioModField;
        
        private string sLogFechaModField;
        
        private string sLogHoraModField;
        
        private string sFlgUsuarioPinPadField;
        
        private string sPwdUsuarioPinpadField;
        
        /// <remarks/>
        public string SCodUsuario {
            get {
                return this.sCodUsuarioField;
            }
            set {
                this.sCodUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string SNomUsuario {
            get {
                return this.sNomUsuarioField;
            }
            set {
                this.sNomUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string SApeUsuario {
            get {
                return this.sApeUsuarioField;
            }
            set {
                this.sApeUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string SCtaUsuario {
            get {
                return this.sCtaUsuarioField;
            }
            set {
                this.sCtaUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string SPwdActualUsuario {
            get {
                return this.sPwdActualUsuarioField;
            }
            set {
                this.sPwdActualUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string SFlgCambioClave {
            get {
                return this.sFlgCambioClaveField;
            }
            set {
                this.sFlgCambioClaveField = value;
            }
        }
        
        /// <remarks/>
        public string STipoEstadoActual {
            get {
                return this.sTipoEstadoActualField;
            }
            set {
                this.sTipoEstadoActualField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtFchVigencia {
            get {
                return this.dtFchVigenciaField;
            }
            set {
                this.dtFchVigenciaField = value;
            }
        }
        
        /// <remarks/>
        public string STipoGrupo {
            get {
                return this.sTipoGrupoField;
            }
            set {
                this.sTipoGrupoField = value;
            }
        }
        
        /// <remarks/>
        public string SDscEstadoActual {
            get {
                return this.sDscEstadoActualField;
            }
            set {
                this.sDscEstadoActualField = value;
            }
        }
        
        /// <remarks/>
        public string SDscGrupo {
            get {
                return this.sDscGrupoField;
            }
            set {
                this.sDscGrupoField = value;
            }
        }
        
        /// <remarks/>
        public string SFchCreacion {
            get {
                return this.sFchCreacionField;
            }
            set {
                this.sFchCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string SHoraCreacion {
            get {
                return this.sHoraCreacionField;
            }
            set {
                this.sHoraCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string SCodUsuarioCreacion {
            get {
                return this.sCodUsuarioCreacionField;
            }
            set {
                this.sCodUsuarioCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string SLogUsuarioMod {
            get {
                return this.sLogUsuarioModField;
            }
            set {
                this.sLogUsuarioModField = value;
            }
        }
        
        /// <remarks/>
        public string SLogFechaMod {
            get {
                return this.sLogFechaModField;
            }
            set {
                this.sLogFechaModField = value;
            }
        }
        
        /// <remarks/>
        public string SLogHoraMod {
            get {
                return this.sLogHoraModField;
            }
            set {
                this.sLogHoraModField = value;
            }
        }
        
        /// <remarks/>
        public string SFlgUsuarioPinPad {
            get {
                return this.sFlgUsuarioPinPadField;
            }
            set {
                this.sFlgUsuarioPinPadField = value;
            }
        }
        
        /// <remarks/>
        public string SPwdUsuarioPinpad {
            get {
                return this.sPwdUsuarioPinpadField;
            }
            set {
                this.sPwdUsuarioPinpadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Moneda {
        
        private string sCodMonedaField;
        
        private string sDscMonedaField;
        
        private string sDscSimboloField;
        
        private string sNemonicoField;
        
        private string sLogUsuarioModField;
        
        private string dtLogFechaModField;
        
        private string sLogHoraModField;
        
        private string sTipEstadoField;
        
        private string sModuloField;
        
        private string sSubModuloField;
        
        /// <remarks/>
        public string SCodMoneda {
            get {
                return this.sCodMonedaField;
            }
            set {
                this.sCodMonedaField = value;
            }
        }
        
        /// <remarks/>
        public string SDscMoneda {
            get {
                return this.sDscMonedaField;
            }
            set {
                this.sDscMonedaField = value;
            }
        }
        
        /// <remarks/>
        public string SDscSimbolo {
            get {
                return this.sDscSimboloField;
            }
            set {
                this.sDscSimboloField = value;
            }
        }
        
        /// <remarks/>
        public string SNemonico {
            get {
                return this.sNemonicoField;
            }
            set {
                this.sNemonicoField = value;
            }
        }
        
        /// <remarks/>
        public string SLogUsuarioMod {
            get {
                return this.sLogUsuarioModField;
            }
            set {
                this.sLogUsuarioModField = value;
            }
        }
        
        /// <remarks/>
        public string DtLogFechaMod {
            get {
                return this.dtLogFechaModField;
            }
            set {
                this.dtLogFechaModField = value;
            }
        }
        
        /// <remarks/>
        public string SLogHoraMod {
            get {
                return this.sLogHoraModField;
            }
            set {
                this.sLogHoraModField = value;
            }
        }
        
        /// <remarks/>
        public string STipEstado {
            get {
                return this.sTipEstadoField;
            }
            set {
                this.sTipEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string SModulo {
            get {
                return this.sModuloField;
            }
            set {
                this.sModuloField = value;
            }
        }
        
        /// <remarks/>
        public string SSubModulo {
            get {
                return this.sSubModuloField;
            }
            set {
                this.sSubModuloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TurnoMonto {
        
        private decimal dImpMontoInicialField;
        
        private decimal dImpMontoFinalField;
        
        private decimal dImpMontoActualField;
        
        private string sCodTurnoField;
        
        private string sCodMonedaField;
        
        private string dscMonedaField;
        
        private string dscSimboloField;
        
        private decimal imp_TransferenciaField;
        
        private decimal imp_ChequeField;
        
        private decimal imp_TarjetaField;
        
        private string tip_PagoField;
        
        /// <remarks/>
        public decimal DImpMontoInicial {
            get {
                return this.dImpMontoInicialField;
            }
            set {
                this.dImpMontoInicialField = value;
            }
        }
        
        /// <remarks/>
        public decimal DImpMontoFinal {
            get {
                return this.dImpMontoFinalField;
            }
            set {
                this.dImpMontoFinalField = value;
            }
        }
        
        /// <remarks/>
        public decimal DImpMontoActual {
            get {
                return this.dImpMontoActualField;
            }
            set {
                this.dImpMontoActualField = value;
            }
        }
        
        /// <remarks/>
        public string SCodTurno {
            get {
                return this.sCodTurnoField;
            }
            set {
                this.sCodTurnoField = value;
            }
        }
        
        /// <remarks/>
        public string SCodMoneda {
            get {
                return this.sCodMonedaField;
            }
            set {
                this.sCodMonedaField = value;
            }
        }
        
        /// <remarks/>
        public string DscMoneda {
            get {
                return this.dscMonedaField;
            }
            set {
                this.dscMonedaField = value;
            }
        }
        
        /// <remarks/>
        public string DscSimbolo {
            get {
                return this.dscSimboloField;
            }
            set {
                this.dscSimboloField = value;
            }
        }
        
        /// <remarks/>
        public decimal Imp_Transferencia {
            get {
                return this.imp_TransferenciaField;
            }
            set {
                this.imp_TransferenciaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Imp_Cheque {
            get {
                return this.imp_ChequeField;
            }
            set {
                this.imp_ChequeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Imp_Tarjeta {
            get {
                return this.imp_TarjetaField;
            }
            set {
                this.imp_TarjetaField = value;
            }
        }
        
        /// <remarks/>
        public string Tip_Pago {
            get {
                return this.tip_PagoField;
            }
            set {
                this.tip_PagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Turno {
        
        private string sCodTurnoField;
        
        private string dtFchInicioField;
        
        private string dtFchFinField;
        
        private string sCodUsuarioCierreField;
        
        private string sCodUsuarioField;
        
        private string sCodEquipoField;
        
        private string sHoraInicioField;
        
        private string sHoraFinField;
        
        /// <remarks/>
        public string SCodTurno {
            get {
                return this.sCodTurnoField;
            }
            set {
                this.sCodTurnoField = value;
            }
        }
        
        /// <remarks/>
        public string DtFchInicio {
            get {
                return this.dtFchInicioField;
            }
            set {
                this.dtFchInicioField = value;
            }
        }
        
        /// <remarks/>
        public string DtFchFin {
            get {
                return this.dtFchFinField;
            }
            set {
                this.dtFchFinField = value;
            }
        }
        
        /// <remarks/>
        public string SCodUsuarioCierre {
            get {
                return this.sCodUsuarioCierreField;
            }
            set {
                this.sCodUsuarioCierreField = value;
            }
        }
        
        /// <remarks/>
        public string SCodUsuario {
            get {
                return this.sCodUsuarioField;
            }
            set {
                this.sCodUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string SCodEquipo {
            get {
                return this.sCodEquipoField;
            }
            set {
                this.sCodEquipoField = value;
            }
        }
        
        /// <remarks/>
        public string SHoraInicio {
            get {
                return this.sHoraInicioField;
            }
            set {
                this.sHoraInicioField = value;
            }
        }
        
        /// <remarks/>
        public string SHoraFin {
            get {
                return this.sHoraFinField;
            }
            set {
                this.sHoraFinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void autenticarCompletedEventHandler(object sender, autenticarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class autenticarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal autenticarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void crearTurnoCompletedEventHandler(object sender, crearTurnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearTurnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearTurnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strTurnoError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ActualizarTurnoCompletedEventHandler(object sender, ActualizarTurnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarTurnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarTurnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void obtenerTurnoIniciadoCompletedEventHandler(object sender, obtenerTurnoIniciadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerTurnoIniciadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerTurnoIniciadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Turno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Turno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void registrarTurnoMontoCompletedEventHandler(object sender, registrarTurnoMontoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarTurnoMontoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarTurnoMontoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ActualizarTurnoMontoCompletedEventHandler(object sender, ActualizarTurnoMontoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarTurnoMontoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarTurnoMontoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void verificarTurnoCerradoxUsuarioCompletedEventHandler(object sender, verificarTurnoCerradoxUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificarTurnoCerradoxUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificarTurnoCerradoxUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void verificarTurnoCerradoxPtoVentaCompletedEventHandler(object sender, verificarTurnoCerradoxPtoVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificarTurnoCerradoxPtoVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificarTurnoCerradoxPtoVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ListarMonedasCompletedEventHandler(object sender, ListarMonedasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarMonedasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarMonedasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Moneda[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Moneda[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ListarTurnoMontosPorTurnoCompletedEventHandler(object sender, ListarTurnoMontosPorTurnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTurnoMontosPorTurnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTurnoMontosPorTurnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TurnoMonto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TurnoMonto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ListarTasaCambioCompletedEventHandler(object sender, ListarTasaCambioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTasaCambioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTasaCambioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591