//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LAP.Tuua.Web.WSDAOConsulta {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSConsultasSoap", Namespace="http://www.lap.com.pe/")]
    public partial class WSConsultas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaBcbpMensualLeidosMolineteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarBoardingLeidosMolineteOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarCamposxNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback DetalleBoardingHistoricaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DetalleBoardingEstHistOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarBoardingAsociadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarParametrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarCompaniaBCBPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBcbpMensualLeidosMolineteXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarBoardingLeidosMolineteXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarCamposxNombreXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback DetalleBoardingHistoricaXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback DetalleBoardingEstHistXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarBoardingAsociadosXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarParametrosXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarCompaniaBCBPXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarBoardingDiarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSConsultas() {
            this.Url = global::LAP.Tuua.Web.Properties.Settings.Default.LAP_Tuua_Web_WSDAOConsulta_WSConsultas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaBcbpMensualLeidosMolineteCompletedEventHandler ConsultaBcbpMensualLeidosMolineteCompleted;
        
        /// <remarks/>
        public event ConsultarBoardingLeidosMolineteCompletedEventHandler ConsultarBoardingLeidosMolineteCompleted;
        
        /// <remarks/>
        public event listarCamposxNombreCompletedEventHandler listarCamposxNombreCompleted;
        
        /// <remarks/>
        public event DetalleBoardingHistoricaCompletedEventHandler DetalleBoardingHistoricaCompleted;
        
        /// <remarks/>
        public event DetalleBoardingEstHistCompletedEventHandler DetalleBoardingEstHistCompleted;
        
        /// <remarks/>
        public event ListarBoardingAsociadosCompletedEventHandler ListarBoardingAsociadosCompleted;
        
        /// <remarks/>
        public event ListarParametrosCompletedEventHandler ListarParametrosCompleted;
        
        /// <remarks/>
        public event ValidarCompaniaBCBPCompletedEventHandler ValidarCompaniaBCBPCompleted;
        
        /// <remarks/>
        public event ConsultaBcbpMensualLeidosMolineteXMLCompletedEventHandler ConsultaBcbpMensualLeidosMolineteXMLCompleted;
        
        /// <remarks/>
        public event ConsultarBoardingLeidosMolineteXMLCompletedEventHandler ConsultarBoardingLeidosMolineteXMLCompleted;
        
        /// <remarks/>
        public event listarCamposxNombreXMLCompletedEventHandler listarCamposxNombreXMLCompleted;
        
        /// <remarks/>
        public event DetalleBoardingHistoricaXMLCompletedEventHandler DetalleBoardingHistoricaXMLCompleted;
        
        /// <remarks/>
        public event DetalleBoardingEstHistXMLCompletedEventHandler DetalleBoardingEstHistXMLCompleted;
        
        /// <remarks/>
        public event ListarBoardingAsociadosXMLCompletedEventHandler ListarBoardingAsociadosXMLCompleted;
        
        /// <remarks/>
        public event ListarParametrosXMLCompletedEventHandler ListarParametrosXMLCompleted;
        
        /// <remarks/>
        public event ValidarCompaniaBCBPXMLCompletedEventHandler ValidarCompaniaBCBPXMLCompleted;
        
        /// <remarks/>
        public event ListarBoardingDiarioCompletedEventHandler ListarBoardingDiarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/ConsultaBcbpMensualLeidosMolinete", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaBcbpMensualLeidosMolinete(string sFchDesde, string sFchHasta, string sNumVuelo, string sTipVuelo, string sTipPersona, string sCodIATA, string sSort, int iFila, int iMaxFila, string sPaginacion, string sMostrarResumen, string sTotalRows, string sExcel) {
            object[] results = this.Invoke("ConsultaBcbpMensualLeidosMolinete", new object[] {
                        sFchDesde,
                        sFchHasta,
                        sNumVuelo,
                        sTipVuelo,
                        sTipPersona,
                        sCodIATA,
                        sSort,
                        iFila,
                        iMaxFila,
                        sPaginacion,
                        sMostrarResumen,
                        sTotalRows,
                        sExcel});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBcbpMensualLeidosMolineteAsync(string sFchDesde, string sFchHasta, string sNumVuelo, string sTipVuelo, string sTipPersona, string sCodIATA, string sSort, int iFila, int iMaxFila, string sPaginacion, string sMostrarResumen, string sTotalRows, string sExcel) {
            this.ConsultaBcbpMensualLeidosMolineteAsync(sFchDesde, sFchHasta, sNumVuelo, sTipVuelo, sTipPersona, sCodIATA, sSort, iFila, iMaxFila, sPaginacion, sMostrarResumen, sTotalRows, sExcel, null);
        }
        
        /// <remarks/>
        public void ConsultaBcbpMensualLeidosMolineteAsync(string sFchDesde, string sFchHasta, string sNumVuelo, string sTipVuelo, string sTipPersona, string sCodIATA, string sSort, int iFila, int iMaxFila, string sPaginacion, string sMostrarResumen, string sTotalRows, string sExcel, object userState) {
            if ((this.ConsultaBcbpMensualLeidosMolineteOperationCompleted == null)) {
                this.ConsultaBcbpMensualLeidosMolineteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBcbpMensualLeidosMolineteOperationCompleted);
            }
            this.InvokeAsync("ConsultaBcbpMensualLeidosMolinete", new object[] {
                        sFchDesde,
                        sFchHasta,
                        sNumVuelo,
                        sTipVuelo,
                        sTipPersona,
                        sCodIATA,
                        sSort,
                        iFila,
                        iMaxFila,
                        sPaginacion,
                        sMostrarResumen,
                        sTotalRows,
                        sExcel}, this.ConsultaBcbpMensualLeidosMolineteOperationCompleted, userState);
        }
        
        private void OnConsultaBcbpMensualLeidosMolineteOperationCompleted(object arg) {
            if ((this.ConsultaBcbpMensualLeidosMolineteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBcbpMensualLeidosMolineteCompleted(this, new ConsultaBcbpMensualLeidosMolineteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/ConsultarBoardingLeidosMolinete", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultarBoardingLeidosMolinete(
                    string sFchDesde, 
                    string sFchHasta, 
                    string sHoraDesde, 
                    string sHoraHasta, 
                    string sFchVuelo, 
                    string sNumVuelo, 
                    string sNumAsiento, 
                    string sNomPasajero, 
                    string sNroBoarding, 
                    string sEticket, 
                    string sEstado, 
                    string sCodIATA, 
                    string sSort, 
                    int iFila, 
                    int iMaxFila, 
                    string sPaginacion, 
                    string sMostrarResumen, 
                    string sFlagTotalRows, 
                    string sFlgExcel) {
            object[] results = this.Invoke("ConsultarBoardingLeidosMolinete", new object[] {
                        sFchDesde,
                        sFchHasta,
                        sHoraDesde,
                        sHoraHasta,
                        sFchVuelo,
                        sNumVuelo,
                        sNumAsiento,
                        sNomPasajero,
                        sNroBoarding,
                        sEticket,
                        sEstado,
                        sCodIATA,
                        sSort,
                        iFila,
                        iMaxFila,
                        sPaginacion,
                        sMostrarResumen,
                        sFlagTotalRows,
                        sFlgExcel});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarBoardingLeidosMolineteAsync(
                    string sFchDesde, 
                    string sFchHasta, 
                    string sHoraDesde, 
                    string sHoraHasta, 
                    string sFchVuelo, 
                    string sNumVuelo, 
                    string sNumAsiento, 
                    string sNomPasajero, 
                    string sNroBoarding, 
                    string sEticket, 
                    string sEstado, 
                    string sCodIATA, 
                    string sSort, 
                    int iFila, 
                    int iMaxFila, 
                    string sPaginacion, 
                    string sMostrarResumen, 
                    string sFlagTotalRows, 
                    string sFlgExcel) {
            this.ConsultarBoardingLeidosMolineteAsync(sFchDesde, sFchHasta, sHoraDesde, sHoraHasta, sFchVuelo, sNumVuelo, sNumAsiento, sNomPasajero, sNroBoarding, sEticket, sEstado, sCodIATA, sSort, iFila, iMaxFila, sPaginacion, sMostrarResumen, sFlagTotalRows, sFlgExcel, null);
        }
        
        /// <remarks/>
        public void ConsultarBoardingLeidosMolineteAsync(
                    string sFchDesde, 
                    string sFchHasta, 
                    string sHoraDesde, 
                    string sHoraHasta, 
                    string sFchVuelo, 
                    string sNumVuelo, 
                    string sNumAsiento, 
                    string sNomPasajero, 
                    string sNroBoarding, 
                    string sEticket, 
                    string sEstado, 
                    string sCodIATA, 
                    string sSort, 
                    int iFila, 
                    int iMaxFila, 
                    string sPaginacion, 
                    string sMostrarResumen, 
                    string sFlagTotalRows, 
                    string sFlgExcel, 
                    object userState) {
            if ((this.ConsultarBoardingLeidosMolineteOperationCompleted == null)) {
                this.ConsultarBoardingLeidosMolineteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarBoardingLeidosMolineteOperationCompleted);
            }
            this.InvokeAsync("ConsultarBoardingLeidosMolinete", new object[] {
                        sFchDesde,
                        sFchHasta,
                        sHoraDesde,
                        sHoraHasta,
                        sFchVuelo,
                        sNumVuelo,
                        sNumAsiento,
                        sNomPasajero,
                        sNroBoarding,
                        sEticket,
                        sEstado,
                        sCodIATA,
                        sSort,
                        iFila,
                        iMaxFila,
                        sPaginacion,
                        sMostrarResumen,
                        sFlagTotalRows,
                        sFlgExcel}, this.ConsultarBoardingLeidosMolineteOperationCompleted, userState);
        }
        
        private void OnConsultarBoardingLeidosMolineteOperationCompleted(object arg) {
            if ((this.ConsultarBoardingLeidosMolineteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarBoardingLeidosMolineteCompleted(this, new ConsultarBoardingLeidosMolineteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/listarCamposxNombre", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable listarCamposxNombre(string sCampos) {
            object[] results = this.Invoke("listarCamposxNombre", new object[] {
                        sCampos});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void listarCamposxNombreAsync(string sCampos) {
            this.listarCamposxNombreAsync(sCampos, null);
        }
        
        /// <remarks/>
        public void listarCamposxNombreAsync(string sCampos, object userState) {
            if ((this.listarCamposxNombreOperationCompleted == null)) {
                this.listarCamposxNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarCamposxNombreOperationCompleted);
            }
            this.InvokeAsync("listarCamposxNombre", new object[] {
                        sCampos}, this.listarCamposxNombreOperationCompleted, userState);
        }
        
        private void OnlistarCamposxNombreOperationCompleted(object arg) {
            if ((this.listarCamposxNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarCamposxNombreCompleted(this, new listarCamposxNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/DetalleBoardingHistorica", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DetalleBoardingHistorica(string Num_Secuencial_Bcbp) {
            object[] results = this.Invoke("DetalleBoardingHistorica", new object[] {
                        Num_Secuencial_Bcbp});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DetalleBoardingHistoricaAsync(string Num_Secuencial_Bcbp) {
            this.DetalleBoardingHistoricaAsync(Num_Secuencial_Bcbp, null);
        }
        
        /// <remarks/>
        public void DetalleBoardingHistoricaAsync(string Num_Secuencial_Bcbp, object userState) {
            if ((this.DetalleBoardingHistoricaOperationCompleted == null)) {
                this.DetalleBoardingHistoricaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDetalleBoardingHistoricaOperationCompleted);
            }
            this.InvokeAsync("DetalleBoardingHistorica", new object[] {
                        Num_Secuencial_Bcbp}, this.DetalleBoardingHistoricaOperationCompleted, userState);
        }
        
        private void OnDetalleBoardingHistoricaOperationCompleted(object arg) {
            if ((this.DetalleBoardingHistoricaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DetalleBoardingHistoricaCompleted(this, new DetalleBoardingHistoricaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/DetalleBoardingEstHist", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DetalleBoardingEstHist(string Num_Secuencial_Bcbp) {
            object[] results = this.Invoke("DetalleBoardingEstHist", new object[] {
                        Num_Secuencial_Bcbp});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DetalleBoardingEstHistAsync(string Num_Secuencial_Bcbp) {
            this.DetalleBoardingEstHistAsync(Num_Secuencial_Bcbp, null);
        }
        
        /// <remarks/>
        public void DetalleBoardingEstHistAsync(string Num_Secuencial_Bcbp, object userState) {
            if ((this.DetalleBoardingEstHistOperationCompleted == null)) {
                this.DetalleBoardingEstHistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDetalleBoardingEstHistOperationCompleted);
            }
            this.InvokeAsync("DetalleBoardingEstHist", new object[] {
                        Num_Secuencial_Bcbp}, this.DetalleBoardingEstHistOperationCompleted, userState);
        }
        
        private void OnDetalleBoardingEstHistOperationCompleted(object arg) {
            if ((this.DetalleBoardingEstHistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DetalleBoardingEstHistCompleted(this, new DetalleBoardingEstHistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/ListarBoardingAsociados", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ListarBoardingAsociados(string Num_Secuencial_Bcbp) {
            object[] results = this.Invoke("ListarBoardingAsociados", new object[] {
                        Num_Secuencial_Bcbp});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ListarBoardingAsociadosAsync(string Num_Secuencial_Bcbp) {
            this.ListarBoardingAsociadosAsync(Num_Secuencial_Bcbp, null);
        }
        
        /// <remarks/>
        public void ListarBoardingAsociadosAsync(string Num_Secuencial_Bcbp, object userState) {
            if ((this.ListarBoardingAsociadosOperationCompleted == null)) {
                this.ListarBoardingAsociadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarBoardingAsociadosOperationCompleted);
            }
            this.InvokeAsync("ListarBoardingAsociados", new object[] {
                        Num_Secuencial_Bcbp}, this.ListarBoardingAsociadosOperationCompleted, userState);
        }
        
        private void OnListarBoardingAsociadosOperationCompleted(object arg) {
            if ((this.ListarBoardingAsociadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarBoardingAsociadosCompleted(this, new ListarBoardingAsociadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/ListarParametros", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ListarParametros(string sIdentificador) {
            object[] results = this.Invoke("ListarParametros", new object[] {
                        sIdentificador});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ListarParametrosAsync(string sIdentificador) {
            this.ListarParametrosAsync(sIdentificador, null);
        }
        
        /// <remarks/>
        public void ListarParametrosAsync(string sIdentificador, object userState) {
            if ((this.ListarParametrosOperationCompleted == null)) {
                this.ListarParametrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarParametrosOperationCompleted);
            }
            this.InvokeAsync("ListarParametros", new object[] {
                        sIdentificador}, this.ListarParametrosOperationCompleted, userState);
        }
        
        private void OnListarParametrosOperationCompleted(object arg) {
            if ((this.ListarParametrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarParametrosCompleted(this, new ListarParametrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/ValidarCompaniaBCBP", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ValidarCompaniaBCBP(string sCod_IATA) {
            object[] results = this.Invoke("ValidarCompaniaBCBP", new object[] {
                        sCod_IATA});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarCompaniaBCBPAsync(string sCod_IATA) {
            this.ValidarCompaniaBCBPAsync(sCod_IATA, null);
        }
        
        /// <remarks/>
        public void ValidarCompaniaBCBPAsync(string sCod_IATA, object userState) {
            if ((this.ValidarCompaniaBCBPOperationCompleted == null)) {
                this.ValidarCompaniaBCBPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarCompaniaBCBPOperationCompleted);
            }
            this.InvokeAsync("ValidarCompaniaBCBP", new object[] {
                        sCod_IATA}, this.ValidarCompaniaBCBPOperationCompleted, userState);
        }
        
        private void OnValidarCompaniaBCBPOperationCompleted(object arg) {
            if ((this.ValidarCompaniaBCBPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarCompaniaBCBPCompleted(this, new ValidarCompaniaBCBPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/ConsultaBcbpMensualLeidosMolineteXML", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaBcbpMensualLeidosMolineteXML(string sFchDesde, string sFchHasta, string sNumVuelo, string sTipVuelo, string sTipPersona, string sCodIATA, string sSort, int iFila, int iMaxFila, string sPaginacion, string sMostrarResumen, string sTotalRows, string sExcel) {
            object[] results = this.Invoke("ConsultaBcbpMensualLeidosMolineteXML", new object[] {
                        sFchDesde,
                        sFchHasta,
                        sNumVuelo,
                        sTipVuelo,
                        sTipPersona,
                        sCodIATA,
                        sSort,
                        iFila,
                        iMaxFila,
                        sPaginacion,
                        sMostrarResumen,
                        sTotalRows,
                        sExcel});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBcbpMensualLeidosMolineteXMLAsync(string sFchDesde, string sFchHasta, string sNumVuelo, string sTipVuelo, string sTipPersona, string sCodIATA, string sSort, int iFila, int iMaxFila, string sPaginacion, string sMostrarResumen, string sTotalRows, string sExcel) {
            this.ConsultaBcbpMensualLeidosMolineteXMLAsync(sFchDesde, sFchHasta, sNumVuelo, sTipVuelo, sTipPersona, sCodIATA, sSort, iFila, iMaxFila, sPaginacion, sMostrarResumen, sTotalRows, sExcel, null);
        }
        
        /// <remarks/>
        public void ConsultaBcbpMensualLeidosMolineteXMLAsync(string sFchDesde, string sFchHasta, string sNumVuelo, string sTipVuelo, string sTipPersona, string sCodIATA, string sSort, int iFila, int iMaxFila, string sPaginacion, string sMostrarResumen, string sTotalRows, string sExcel, object userState) {
            if ((this.ConsultaBcbpMensualLeidosMolineteXMLOperationCompleted == null)) {
                this.ConsultaBcbpMensualLeidosMolineteXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBcbpMensualLeidosMolineteXMLOperationCompleted);
            }
            this.InvokeAsync("ConsultaBcbpMensualLeidosMolineteXML", new object[] {
                        sFchDesde,
                        sFchHasta,
                        sNumVuelo,
                        sTipVuelo,
                        sTipPersona,
                        sCodIATA,
                        sSort,
                        iFila,
                        iMaxFila,
                        sPaginacion,
                        sMostrarResumen,
                        sTotalRows,
                        sExcel}, this.ConsultaBcbpMensualLeidosMolineteXMLOperationCompleted, userState);
        }
        
        private void OnConsultaBcbpMensualLeidosMolineteXMLOperationCompleted(object arg) {
            if ((this.ConsultaBcbpMensualLeidosMolineteXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBcbpMensualLeidosMolineteXMLCompleted(this, new ConsultaBcbpMensualLeidosMolineteXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/ConsultarBoardingLeidosMolineteXML", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultarBoardingLeidosMolineteXML(
                    string sFchDesde, 
                    string sFchHasta, 
                    string sHoraDesde, 
                    string sHoraHasta, 
                    string sFchVuelo, 
                    string sNumVuelo, 
                    string sNumAsiento, 
                    string sNomPasajero, 
                    string sNroBoarding, 
                    string sEticket, 
                    string sEstado, 
                    string sCodIATA, 
                    string sSort, 
                    int iFila, 
                    int iMaxFila, 
                    string sPaginacion, 
                    string sMostrarResumen, 
                    string sFlagTotalRows, 
                    string sFlgExcel) {
            object[] results = this.Invoke("ConsultarBoardingLeidosMolineteXML", new object[] {
                        sFchDesde,
                        sFchHasta,
                        sHoraDesde,
                        sHoraHasta,
                        sFchVuelo,
                        sNumVuelo,
                        sNumAsiento,
                        sNomPasajero,
                        sNroBoarding,
                        sEticket,
                        sEstado,
                        sCodIATA,
                        sSort,
                        iFila,
                        iMaxFila,
                        sPaginacion,
                        sMostrarResumen,
                        sFlagTotalRows,
                        sFlgExcel});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarBoardingLeidosMolineteXMLAsync(
                    string sFchDesde, 
                    string sFchHasta, 
                    string sHoraDesde, 
                    string sHoraHasta, 
                    string sFchVuelo, 
                    string sNumVuelo, 
                    string sNumAsiento, 
                    string sNomPasajero, 
                    string sNroBoarding, 
                    string sEticket, 
                    string sEstado, 
                    string sCodIATA, 
                    string sSort, 
                    int iFila, 
                    int iMaxFila, 
                    string sPaginacion, 
                    string sMostrarResumen, 
                    string sFlagTotalRows, 
                    string sFlgExcel) {
            this.ConsultarBoardingLeidosMolineteXMLAsync(sFchDesde, sFchHasta, sHoraDesde, sHoraHasta, sFchVuelo, sNumVuelo, sNumAsiento, sNomPasajero, sNroBoarding, sEticket, sEstado, sCodIATA, sSort, iFila, iMaxFila, sPaginacion, sMostrarResumen, sFlagTotalRows, sFlgExcel, null);
        }
        
        /// <remarks/>
        public void ConsultarBoardingLeidosMolineteXMLAsync(
                    string sFchDesde, 
                    string sFchHasta, 
                    string sHoraDesde, 
                    string sHoraHasta, 
                    string sFchVuelo, 
                    string sNumVuelo, 
                    string sNumAsiento, 
                    string sNomPasajero, 
                    string sNroBoarding, 
                    string sEticket, 
                    string sEstado, 
                    string sCodIATA, 
                    string sSort, 
                    int iFila, 
                    int iMaxFila, 
                    string sPaginacion, 
                    string sMostrarResumen, 
                    string sFlagTotalRows, 
                    string sFlgExcel, 
                    object userState) {
            if ((this.ConsultarBoardingLeidosMolineteXMLOperationCompleted == null)) {
                this.ConsultarBoardingLeidosMolineteXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarBoardingLeidosMolineteXMLOperationCompleted);
            }
            this.InvokeAsync("ConsultarBoardingLeidosMolineteXML", new object[] {
                        sFchDesde,
                        sFchHasta,
                        sHoraDesde,
                        sHoraHasta,
                        sFchVuelo,
                        sNumVuelo,
                        sNumAsiento,
                        sNomPasajero,
                        sNroBoarding,
                        sEticket,
                        sEstado,
                        sCodIATA,
                        sSort,
                        iFila,
                        iMaxFila,
                        sPaginacion,
                        sMostrarResumen,
                        sFlagTotalRows,
                        sFlgExcel}, this.ConsultarBoardingLeidosMolineteXMLOperationCompleted, userState);
        }
        
        private void OnConsultarBoardingLeidosMolineteXMLOperationCompleted(object arg) {
            if ((this.ConsultarBoardingLeidosMolineteXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarBoardingLeidosMolineteXMLCompleted(this, new ConsultarBoardingLeidosMolineteXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/listarCamposxNombreXML", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode listarCamposxNombreXML(string sCampos) {
            object[] results = this.Invoke("listarCamposxNombreXML", new object[] {
                        sCampos});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void listarCamposxNombreXMLAsync(string sCampos) {
            this.listarCamposxNombreXMLAsync(sCampos, null);
        }
        
        /// <remarks/>
        public void listarCamposxNombreXMLAsync(string sCampos, object userState) {
            if ((this.listarCamposxNombreXMLOperationCompleted == null)) {
                this.listarCamposxNombreXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarCamposxNombreXMLOperationCompleted);
            }
            this.InvokeAsync("listarCamposxNombreXML", new object[] {
                        sCampos}, this.listarCamposxNombreXMLOperationCompleted, userState);
        }
        
        private void OnlistarCamposxNombreXMLOperationCompleted(object arg) {
            if ((this.listarCamposxNombreXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarCamposxNombreXMLCompleted(this, new listarCamposxNombreXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/DetalleBoardingHistoricaXML", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode DetalleBoardingHistoricaXML(string Num_Secuencial_Bcbp) {
            object[] results = this.Invoke("DetalleBoardingHistoricaXML", new object[] {
                        Num_Secuencial_Bcbp});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void DetalleBoardingHistoricaXMLAsync(string Num_Secuencial_Bcbp) {
            this.DetalleBoardingHistoricaXMLAsync(Num_Secuencial_Bcbp, null);
        }
        
        /// <remarks/>
        public void DetalleBoardingHistoricaXMLAsync(string Num_Secuencial_Bcbp, object userState) {
            if ((this.DetalleBoardingHistoricaXMLOperationCompleted == null)) {
                this.DetalleBoardingHistoricaXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDetalleBoardingHistoricaXMLOperationCompleted);
            }
            this.InvokeAsync("DetalleBoardingHistoricaXML", new object[] {
                        Num_Secuencial_Bcbp}, this.DetalleBoardingHistoricaXMLOperationCompleted, userState);
        }
        
        private void OnDetalleBoardingHistoricaXMLOperationCompleted(object arg) {
            if ((this.DetalleBoardingHistoricaXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DetalleBoardingHistoricaXMLCompleted(this, new DetalleBoardingHistoricaXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/DetalleBoardingEstHistXML", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode DetalleBoardingEstHistXML(string Num_Secuencial_Bcbp) {
            object[] results = this.Invoke("DetalleBoardingEstHistXML", new object[] {
                        Num_Secuencial_Bcbp});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void DetalleBoardingEstHistXMLAsync(string Num_Secuencial_Bcbp) {
            this.DetalleBoardingEstHistXMLAsync(Num_Secuencial_Bcbp, null);
        }
        
        /// <remarks/>
        public void DetalleBoardingEstHistXMLAsync(string Num_Secuencial_Bcbp, object userState) {
            if ((this.DetalleBoardingEstHistXMLOperationCompleted == null)) {
                this.DetalleBoardingEstHistXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDetalleBoardingEstHistXMLOperationCompleted);
            }
            this.InvokeAsync("DetalleBoardingEstHistXML", new object[] {
                        Num_Secuencial_Bcbp}, this.DetalleBoardingEstHistXMLOperationCompleted, userState);
        }
        
        private void OnDetalleBoardingEstHistXMLOperationCompleted(object arg) {
            if ((this.DetalleBoardingEstHistXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DetalleBoardingEstHistXMLCompleted(this, new DetalleBoardingEstHistXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/ListarBoardingAsociadosXML", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListarBoardingAsociadosXML(string Num_Secuencial_Bcbp) {
            object[] results = this.Invoke("ListarBoardingAsociadosXML", new object[] {
                        Num_Secuencial_Bcbp});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListarBoardingAsociadosXMLAsync(string Num_Secuencial_Bcbp) {
            this.ListarBoardingAsociadosXMLAsync(Num_Secuencial_Bcbp, null);
        }
        
        /// <remarks/>
        public void ListarBoardingAsociadosXMLAsync(string Num_Secuencial_Bcbp, object userState) {
            if ((this.ListarBoardingAsociadosXMLOperationCompleted == null)) {
                this.ListarBoardingAsociadosXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarBoardingAsociadosXMLOperationCompleted);
            }
            this.InvokeAsync("ListarBoardingAsociadosXML", new object[] {
                        Num_Secuencial_Bcbp}, this.ListarBoardingAsociadosXMLOperationCompleted, userState);
        }
        
        private void OnListarBoardingAsociadosXMLOperationCompleted(object arg) {
            if ((this.ListarBoardingAsociadosXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarBoardingAsociadosXMLCompleted(this, new ListarBoardingAsociadosXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/ListarParametrosXML", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListarParametrosXML(string sIdentificador) {
            object[] results = this.Invoke("ListarParametrosXML", new object[] {
                        sIdentificador});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListarParametrosXMLAsync(string sIdentificador) {
            this.ListarParametrosXMLAsync(sIdentificador, null);
        }
        
        /// <remarks/>
        public void ListarParametrosXMLAsync(string sIdentificador, object userState) {
            if ((this.ListarParametrosXMLOperationCompleted == null)) {
                this.ListarParametrosXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarParametrosXMLOperationCompleted);
            }
            this.InvokeAsync("ListarParametrosXML", new object[] {
                        sIdentificador}, this.ListarParametrosXMLOperationCompleted, userState);
        }
        
        private void OnListarParametrosXMLOperationCompleted(object arg) {
            if ((this.ListarParametrosXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarParametrosXMLCompleted(this, new ListarParametrosXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/ValidarCompaniaBCBPXML", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ValidarCompaniaBCBPXML(string sCod_IATA) {
            object[] results = this.Invoke("ValidarCompaniaBCBPXML", new object[] {
                        sCod_IATA});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarCompaniaBCBPXMLAsync(string sCod_IATA) {
            this.ValidarCompaniaBCBPXMLAsync(sCod_IATA, null);
        }
        
        /// <remarks/>
        public void ValidarCompaniaBCBPXMLAsync(string sCod_IATA, object userState) {
            if ((this.ValidarCompaniaBCBPXMLOperationCompleted == null)) {
                this.ValidarCompaniaBCBPXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarCompaniaBCBPXMLOperationCompleted);
            }
            this.InvokeAsync("ValidarCompaniaBCBPXML", new object[] {
                        sCod_IATA}, this.ValidarCompaniaBCBPXMLOperationCompleted, userState);
        }
        
        private void OnValidarCompaniaBCBPXMLOperationCompleted(object arg) {
            if ((this.ValidarCompaniaBCBPXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarCompaniaBCBPXMLCompleted(this, new ValidarCompaniaBCBPXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lap.com.pe/ListarBoardingDiario", RequestNamespace="http://www.lap.com.pe/", ResponseNamespace="http://www.lap.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListarBoardingDiario(
                    string sFechaDesde, 
                    string sFechaHasta, 
                    string sHoraDesde, 
                    string sHoraHasta, 
                    string sCodCompania, 
                    string sTipoPasajero, 
                    string sTipoVuelo, 
                    string sTipoTrasbordo, 
                    string sFechaVuelo, 
                    string sNumVuelo, 
                    string sPasajero, 
                    string sNumAsiento, 
                    string sCodIata, 
                    string sPassword, 
                    string sTipReporte, 
                    string sColumnSort, 
                    int iIniRows, 
                    int iMaxRows, 
                    string sTotalRows) {
            object[] results = this.Invoke("ListarBoardingDiario", new object[] {
                        sFechaDesde,
                        sFechaHasta,
                        sHoraDesde,
                        sHoraHasta,
                        sCodCompania,
                        sTipoPasajero,
                        sTipoVuelo,
                        sTipoTrasbordo,
                        sFechaVuelo,
                        sNumVuelo,
                        sPasajero,
                        sNumAsiento,
                        sCodIata,
                        sPassword,
                        sTipReporte,
                        sColumnSort,
                        iIniRows,
                        iMaxRows,
                        sTotalRows});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListarBoardingDiarioAsync(
                    string sFechaDesde, 
                    string sFechaHasta, 
                    string sHoraDesde, 
                    string sHoraHasta, 
                    string sCodCompania, 
                    string sTipoPasajero, 
                    string sTipoVuelo, 
                    string sTipoTrasbordo, 
                    string sFechaVuelo, 
                    string sNumVuelo, 
                    string sPasajero, 
                    string sNumAsiento, 
                    string sCodIata, 
                    string sPassword, 
                    string sTipReporte, 
                    string sColumnSort, 
                    int iIniRows, 
                    int iMaxRows, 
                    string sTotalRows) {
            this.ListarBoardingDiarioAsync(sFechaDesde, sFechaHasta, sHoraDesde, sHoraHasta, sCodCompania, sTipoPasajero, sTipoVuelo, sTipoTrasbordo, sFechaVuelo, sNumVuelo, sPasajero, sNumAsiento, sCodIata, sPassword, sTipReporte, sColumnSort, iIniRows, iMaxRows, sTotalRows, null);
        }
        
        /// <remarks/>
        public void ListarBoardingDiarioAsync(
                    string sFechaDesde, 
                    string sFechaHasta, 
                    string sHoraDesde, 
                    string sHoraHasta, 
                    string sCodCompania, 
                    string sTipoPasajero, 
                    string sTipoVuelo, 
                    string sTipoTrasbordo, 
                    string sFechaVuelo, 
                    string sNumVuelo, 
                    string sPasajero, 
                    string sNumAsiento, 
                    string sCodIata, 
                    string sPassword, 
                    string sTipReporte, 
                    string sColumnSort, 
                    int iIniRows, 
                    int iMaxRows, 
                    string sTotalRows, 
                    object userState) {
            if ((this.ListarBoardingDiarioOperationCompleted == null)) {
                this.ListarBoardingDiarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarBoardingDiarioOperationCompleted);
            }
            this.InvokeAsync("ListarBoardingDiario", new object[] {
                        sFechaDesde,
                        sFechaHasta,
                        sHoraDesde,
                        sHoraHasta,
                        sCodCompania,
                        sTipoPasajero,
                        sTipoVuelo,
                        sTipoTrasbordo,
                        sFechaVuelo,
                        sNumVuelo,
                        sPasajero,
                        sNumAsiento,
                        sCodIata,
                        sPassword,
                        sTipReporte,
                        sColumnSort,
                        iIniRows,
                        iMaxRows,
                        sTotalRows}, this.ListarBoardingDiarioOperationCompleted, userState);
        }
        
        private void OnListarBoardingDiarioOperationCompleted(object arg) {
            if ((this.ListarBoardingDiarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarBoardingDiarioCompleted(this, new ListarBoardingDiarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ConsultaBcbpMensualLeidosMolineteCompletedEventHandler(object sender, ConsultaBcbpMensualLeidosMolineteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBcbpMensualLeidosMolineteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBcbpMensualLeidosMolineteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ConsultarBoardingLeidosMolineteCompletedEventHandler(object sender, ConsultarBoardingLeidosMolineteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarBoardingLeidosMolineteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarBoardingLeidosMolineteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void listarCamposxNombreCompletedEventHandler(object sender, listarCamposxNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarCamposxNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarCamposxNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DetalleBoardingHistoricaCompletedEventHandler(object sender, DetalleBoardingHistoricaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DetalleBoardingHistoricaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DetalleBoardingHistoricaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DetalleBoardingEstHistCompletedEventHandler(object sender, DetalleBoardingEstHistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DetalleBoardingEstHistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DetalleBoardingEstHistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ListarBoardingAsociadosCompletedEventHandler(object sender, ListarBoardingAsociadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarBoardingAsociadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarBoardingAsociadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ListarParametrosCompletedEventHandler(object sender, ListarParametrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarParametrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarParametrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ValidarCompaniaBCBPCompletedEventHandler(object sender, ValidarCompaniaBCBPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarCompaniaBCBPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarCompaniaBCBPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ConsultaBcbpMensualLeidosMolineteXMLCompletedEventHandler(object sender, ConsultaBcbpMensualLeidosMolineteXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBcbpMensualLeidosMolineteXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBcbpMensualLeidosMolineteXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ConsultarBoardingLeidosMolineteXMLCompletedEventHandler(object sender, ConsultarBoardingLeidosMolineteXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarBoardingLeidosMolineteXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarBoardingLeidosMolineteXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void listarCamposxNombreXMLCompletedEventHandler(object sender, listarCamposxNombreXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarCamposxNombreXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarCamposxNombreXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DetalleBoardingHistoricaXMLCompletedEventHandler(object sender, DetalleBoardingHistoricaXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DetalleBoardingHistoricaXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DetalleBoardingHistoricaXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DetalleBoardingEstHistXMLCompletedEventHandler(object sender, DetalleBoardingEstHistXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DetalleBoardingEstHistXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DetalleBoardingEstHistXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ListarBoardingAsociadosXMLCompletedEventHandler(object sender, ListarBoardingAsociadosXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarBoardingAsociadosXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarBoardingAsociadosXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ListarParametrosXMLCompletedEventHandler(object sender, ListarParametrosXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarParametrosXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarParametrosXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ValidarCompaniaBCBPXMLCompletedEventHandler(object sender, ValidarCompaniaBCBPXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarCompaniaBCBPXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarCompaniaBCBPXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ListarBoardingDiarioCompletedEventHandler(object sender, ListarBoardingDiarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarBoardingDiarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarBoardingDiarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591