// ------------------------------------------------------------------------------
//<autogenerated>
//        This code was generated by Microsoft Visual Studio Team System 2005.
//
//        Changes to this file may cause incorrect behavior and will be lost if
//        the code is regenerated.
//</autogenerated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestAccesos
{
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class BaseAccessor {
    
    protected Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject m_privateObject;
    
    protected BaseAccessor(object target, Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) {
        m_privateObject = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(target, type);
    }
    
    protected BaseAccessor(Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) : 
            this(null, type) {
    }
    
    internal virtual object Target {
        get {
            return m_privateObject.Target;
        }
    }
    
    public override string ToString() {
        return this.Target.ToString();
    }
    
    public override bool Equals(object obj) {
        if (typeof(BaseAccessor).IsInstanceOfType(obj)) {
            obj = ((BaseAccessor)(obj)).Target;
        }
        return this.Target.Equals(obj);
    }
    
    public override int GetHashCode() {
        return this.Target.GetHashCode();
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class ConsoleApplication1_ACS_InterfazLectorAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "ConsoleApplication1.ACS_InterfazLector");
    
    internal ConsoleApplication1_ACS_InterfazLectorAccessor(object target) : 
            base(target, m_privateType) {
    }
    
    internal global::TestAccesos.ConsoleApplication1_ACS_SincronizaLecturaAccessor Obj_SincLector {
        get {
            object _ret_val = m_privateObject.GetField("Obj_SincLector");
            global::TestAccesos.ConsoleApplication1_ACS_SincronizaLecturaAccessor _ret = null;
            if ((_ret_val != null)) {
                _ret = new global::TestAccesos.ConsoleApplication1_ACS_SincronizaLecturaAccessor(_ret_val);
            }
            global::TestAccesos.ConsoleApplication1_ACS_SincronizaLecturaAccessor ret = _ret;
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_SincLector", value);
        }
    }
    
    internal global::ATLCOMLib.Comm Obj_LectorCB {
        get {
            global::ATLCOMLib.Comm ret = ((global::ATLCOMLib.Comm)(m_privateObject.GetField("Obj_LectorCB")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_LectorCB", value);
        }
    }
    
    internal global::System.Collections.Hashtable Arr_PtoLectorConfig {
        get {
            global::System.Collections.Hashtable ret = ((global::System.Collections.Hashtable)(m_privateObject.GetField("Arr_PtoLectorConfig")));
            return ret;
        }
        set {
            m_privateObject.SetField("Arr_PtoLectorConfig", value);
        }
    }
    
    internal global::TestAccesos.ConsoleApplication1_ACS_UtilAccessor Obj_Util {
        get {
            object _ret_val = m_privateObject.GetField("Obj_Util");
            global::TestAccesos.ConsoleApplication1_ACS_UtilAccessor _ret = null;
            if ((_ret_val != null)) {
                _ret = new global::TestAccesos.ConsoleApplication1_ACS_UtilAccessor(_ret_val);
            }
            global::TestAccesos.ConsoleApplication1_ACS_UtilAccessor ret = _ret;
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_Util", value);
        }
    }
    
    internal global::System.Xml.XmlDocument List_FormatoBoarding {
        get {
            global::System.Xml.XmlDocument ret = ((global::System.Xml.XmlDocument)(m_privateObject.GetField("List_FormatoBoarding")));
            return ret;
        }
        set {
            m_privateObject.SetField("List_FormatoBoarding", value);
        }
    }
    
    internal global::LAP.TUUA.ENTIDADES.BoardingBcbp Obj_BoardingBcbp {
        get {
            global::LAP.TUUA.ENTIDADES.BoardingBcbp ret = ((global::LAP.TUUA.ENTIDADES.BoardingBcbp)(m_privateObject.GetField("Obj_BoardingBcbp")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_BoardingBcbp", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_BoardingBcbp Obj_DAOBoardingBcbp {
        get {
              global::LAP.TUUA.DAO.DAO_BoardingBcbp ret = ((global::LAP.TUUA.DAO.DAO_BoardingBcbp)(m_privateObject.GetField("Obj_DAOBoardingBcbp")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOBoardingBcbp", value);
        }
    }
    
    internal global::HCOMHEPSLib.CajaClass Obj_PinPad {
        get {
            global::HCOMHEPSLib.CajaClass ret = ((global::HCOMHEPSLib.CajaClass)(m_privateObject.GetField("Obj_PinPad")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_PinPad", value);
        }
    }
    
    internal global::System.Threading.Thread Obj_HiloInterfazLector {
        get {
            global::System.Threading.Thread ret = ((global::System.Threading.Thread)(m_privateObject.GetField("Obj_HiloInterfazLector")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_HiloInterfazLector", value);
        }
    }
    
    internal global::System.Collections.Hashtable Ht_Boarding {
        get {
            global::System.Collections.Hashtable ret = ((global::System.Collections.Hashtable)(m_privateObject.GetField("Ht_Boarding")));
            return ret;
        }
        set {
            m_privateObject.SetField("Ht_Boarding", value);
        }
    }
    
    internal global::LAP.TUUA.ENTIDADES.BoardingBcbpErr Obj_BoardingBcbpErr {
        get {
            global::LAP.TUUA.ENTIDADES.BoardingBcbpErr ret = ((global::LAP.TUUA.ENTIDADES.BoardingBcbpErr)(m_privateObject.GetField("Obj_BoardingBcbpErr")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_BoardingBcbpErr", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_BoardingBcbpErr Obj_DAOBoardingBcbpErr {
        get {
            global::LAP.TUUA.DAO.DAO_BoardingBcbpErr ret = ((global::LAP.TUUA.DAO.DAO_BoardingBcbpErr)(m_privateObject.GetField("Obj_DAOBoardingBcbpErr")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOBoardingBcbpErr", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_Ticket Obj_DAOTicket {
        get {
            global::LAP.TUUA.DAO.DAO_Ticket ret = ((global::LAP.TUUA.DAO.DAO_Ticket)(m_privateObject.GetField("Obj_DAOTicket")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOTicket", value);
        }
    }
    
    internal global::LAP.TUUA.ENTIDADES.Ticket Obj_Ticket {
        get {
            global::LAP.TUUA.ENTIDADES.Ticket ret = ((global::LAP.TUUA.ENTIDADES.Ticket)(m_privateObject.GetField("Obj_Ticket")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_Ticket", value);
        }
    }
    
    internal string Tip_Trama {
        get {
            string ret = ((string)(m_privateObject.GetField("Tip_Trama")));
            return ret;
        }
        set {
            m_privateObject.SetField("Tip_Trama", value);
        }
    }
    
    internal global::TestAccesos.ConsoleApplication1_ACS_InterfazPinPadAccessor Obj_IntzPinPad {
        get {
            object _ret_val = m_privateObject.GetField("Obj_IntzPinPad");
            global::TestAccesos.ConsoleApplication1_ACS_InterfazPinPadAccessor _ret = null;
            if ((_ret_val != null)) {
                _ret = new global::TestAccesos.ConsoleApplication1_ACS_InterfazPinPadAccessor(_ret_val);
            }
            global::TestAccesos.ConsoleApplication1_ACS_InterfazPinPadAccessor ret = _ret;
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_IntzPinPad", value);
        }
    }
    
    internal static object CreatePrivate(global::TestAccesos.ConsoleApplication1_ACS_SincronizaLecturaAccessor Obj_Sinc, global::System.Collections.Hashtable Arr_Pto, global::System.Xml.XmlDocument listFormatoBoarding, global::HCOMHEPSLib.CajaClass Obj_PinPad, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.Compania> Lst_Compania, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo> Lst_ListaDeCampo, global::TestAccesos.ConsoleApplication1_ACS_InterfazPinPadAccessor Obj_IntzPinPad) {
        object Obj_Sinc_val_target = null;
        if ((Obj_Sinc != null)) {
            Obj_Sinc_val_target = Obj_Sinc.Target;
        }
        object Obj_IntzPinPad_val_target = null;
        if ((Obj_IntzPinPad != null)) {
            Obj_IntzPinPad_val_target = Obj_IntzPinPad.Target;
        }
        object[] args = new object[] {
                Obj_Sinc_val_target,
                Arr_Pto,
                listFormatoBoarding,
                Obj_PinPad,
                Lst_Compania,
                Lst_ListaDeCampo,
                Obj_IntzPinPad_val_target};
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType target_fallback1 = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "ConsoleApplication1.ACS_SincronizaLectura");
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType target_fallback2 = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "ConsoleApplication1.ACS_InterfazPinPad");
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("ACCESOS", "ConsoleApplication1.ACS_InterfazLector", new System.Type[] {
                    target_fallback1.ReferencedType,
                    typeof(global::System.Collections.Hashtable),
                    typeof(global::System.Xml.XmlDocument),
                    typeof(global::HCOMHEPSLib.CajaClass),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.Compania>),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo>),
                    target_fallback2.ReferencedType}, args);
        return priv_obj.Target;
    }
    
    internal void Ejecutar() {
        object[] args = new object[0];
        m_privateObject.Invoke("Ejecutar", new System.Type[0], args);
    }
    
    internal int ProcesarTrama(string strTrama) {
        object[] args = new object[] {
                strTrama};
        int ret = ((int)(m_privateObject.Invoke("ProcesarTrama", new System.Type[] {
                    typeof(string)}, args)));
        return ret;
    }
    
    internal string ObtenerTicket(string strTrama) {
        object[] args = new object[] {
                strTrama};
        string ret = ((string)(m_privateObject.Invoke("ObtenerTicket", new System.Type[] {
                    typeof(string)}, args)));
        return ret;
    }
    
    internal void LeerLectorCB() {
        object[] args = new object[0];
        m_privateObject.Invoke("LeerLectorCB", new System.Type[0], args);
    }
    
    internal int ObtenerTout() {
        object[] args = new object[0];
        int ret = ((int)(m_privateObject.Invoke("ObtenerTout", new System.Type[0], args)));
        return ret;
    }
    
    internal string LeerTrama() {
        object[] args = new object[0];
        string ret = ((string)(m_privateObject.Invoke("LeerTrama", new System.Type[0], args)));
        return ret;
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class ConsoleApplication1_ACS_SincronizaLecturaAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "ConsoleApplication1.ACS_SincronizaLectura");
    
    internal ConsoleApplication1_ACS_SincronizaLecturaAccessor(object target) : 
            base(target, m_privateType) {
    }
    
    internal bool flg_LecturaScaner {
        get {
            bool ret = ((bool)(m_privateObject.GetField("flg_LecturaScaner")));
            return ret;
        }
        set {
            m_privateObject.SetField("flg_LecturaScaner", value);
        }
    }
    
    internal static object CreatePrivate() {
        object[] args = new object[0];
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("ACCESOS", "ConsoleApplication1.ACS_SincronizaLectura", new System.Type[0], args);
        return priv_obj.Target;
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class ConsoleApplication1_ACS_InterfazPinPadAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "ConsoleApplication1.ACS_InterfazPinPad");
    
    internal ConsoleApplication1_ACS_InterfazPinPadAccessor(object target) : 
            base(target, m_privateType) {
    }
    
    internal global::System.Threading.Thread obj_HiloInterfazPinpad {
        get {
            global::System.Threading.Thread ret = ((global::System.Threading.Thread)(m_privateObject.GetField("obj_HiloInterfazPinpad")));
            return ret;
        }
        set {
            m_privateObject.SetField("obj_HiloInterfazPinpad", value);
        }
    }
    
    internal global::TestAccesos.ConsoleApplication1_ACS_SincronizaLecturaAccessor Obj_SincPinPad {
        get {
            object _ret_val = m_privateObject.GetField("Obj_SincPinPad");
            global::TestAccesos.ConsoleApplication1_ACS_SincronizaLecturaAccessor _ret = null;
            if ((_ret_val != null)) {
                _ret = new global::TestAccesos.ConsoleApplication1_ACS_SincronizaLecturaAccessor(_ret_val);
            }
            global::TestAccesos.ConsoleApplication1_ACS_SincronizaLecturaAccessor ret = _ret;
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_SincPinPad", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_Usuario Obj_DAOUsuario {
        get {
            global::LAP.TUUA.DAO.DAO_Usuario ret = ((global::LAP.TUUA.DAO.DAO_Usuario)(m_privateObject.GetField("Obj_DAOUsuario")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOUsuario", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_Ticket Obj_DAOTicket {
        get {
            global::LAP.TUUA.DAO.DAO_Ticket ret = ((global::LAP.TUUA.DAO.DAO_Ticket)(m_privateObject.GetField("Obj_DAOTicket")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOTicket", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_BoardingBcbp Obj_DAOBoardingBcbp {
        get {
            global::LAP.TUUA.DAO.DAO_BoardingBcbp ret = ((global::LAP.TUUA.DAO.DAO_BoardingBcbp)(m_privateObject.GetField("Obj_DAOBoardingBcbp")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOBoardingBcbp", value);
        }
    }
    
    internal global::LAP.TUUA.ENTIDADES.Ticket Obj_Ticket {
        get {
            global::LAP.TUUA.ENTIDADES.Ticket ret = ((global::LAP.TUUA.ENTIDADES.Ticket)(m_privateObject.GetField("Obj_Ticket")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_Ticket", value);
        }
    }
    
    internal global::LAP.TUUA.ENTIDADES.Usuario Obj_Usuario {
        get {
            global::LAP.TUUA.ENTIDADES.Usuario ret = ((global::LAP.TUUA.ENTIDADES.Usuario)(m_privateObject.GetField("Obj_Usuario")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_Usuario", value);
        }
    }
    
    internal global::LAP.TUUA.ENTIDADES.BoardingBcbp Obj_BoardingBcbp {
        get {
            global::LAP.TUUA.ENTIDADES.BoardingBcbp ret = ((global::LAP.TUUA.ENTIDADES.BoardingBcbp)(m_privateObject.GetField("Obj_BoardingBcbp")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_BoardingBcbp", value);
        }
    }
    
    internal global::HCOMHEPSLib.CajaClass Obj_PinPad {
        get {
            global::HCOMHEPSLib.CajaClass ret = ((global::HCOMHEPSLib.CajaClass)(m_privateObject.GetField("Obj_PinPad")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_PinPad", value);
        }
    }
    
    internal global::System.DateTime dt_Fecha {
        get {
            global::System.DateTime ret = ((global::System.DateTime)(m_privateObject.GetField("dt_Fecha")));
            return ret;
        }
        set {
            m_privateObject.SetField("dt_Fecha", value);
        }
    }
    
    internal global::TestAccesos.ConsoleApplication1_ACS_UtilAccessor Obj_Util {
        get {
            object _ret_val = m_privateObject.GetField("Obj_Util");
            global::TestAccesos.ConsoleApplication1_ACS_UtilAccessor _ret = null;
            if ((_ret_val != null)) {
                _ret = new global::TestAccesos.ConsoleApplication1_ACS_UtilAccessor(_ret_val);
            }
            global::TestAccesos.ConsoleApplication1_ACS_UtilAccessor ret = _ret;
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_Util", value);
        }
    }
    
    internal static object CreatePrivate(global::TestAccesos.ConsoleApplication1_ACS_SincronizaLecturaAccessor Obj_Sinc, global::HCOMHEPSLib.CajaClass Obj_PinPad) {
        object Obj_Sinc_val_target = null;
        if ((Obj_Sinc != null)) {
            Obj_Sinc_val_target = Obj_Sinc.Target;
        }
        object[] args = new object[] {
                Obj_Sinc_val_target,
                Obj_PinPad};
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType target = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "ConsoleApplication1.ACS_SincronizaLectura");
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("ACCESOS", "ConsoleApplication1.ACS_InterfazPinPad", new System.Type[] {
                    target.ReferencedType,
                    typeof(global::HCOMHEPSLib.CajaClass)}, args);
        return priv_obj.Target;
    }
    
    internal void Ejecutar() {
        object[] args = new object[0];
        m_privateObject.Invoke("Ejecutar", new System.Type[0], args);
    }
    
    internal void LeerPinPad() {
        object[] args = new object[0];
        m_privateObject.Invoke("LeerPinPad", new System.Type[0], args);
    }
    
    internal void MostrarMensajePinpad(string msgRespuesta, string strCodTransaccion) {
        object[] args = new object[] {
                msgRespuesta,
                strCodTransaccion};
        m_privateObject.Invoke("MostrarMensajePinpad", new System.Type[] {
                    typeof(string),
                    typeof(string)}, args);
    }
    
    internal int MostrarMsgPINPad(string strCodTransaccion, string strMsgDataAdicional, string strMsgDataTrack2) {
        object[] args = new object[] {
                strCodTransaccion,
                strMsgDataAdicional,
                strMsgDataTrack2};
        int ret = ((int)(m_privateObject.Invoke("MostrarMsgPINPad", new System.Type[] {
                    typeof(string),
                    typeof(string),
                    typeof(string)}, args)));
        return ret;
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class ConsoleApplication1_ACS_UtilAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "ConsoleApplication1.ACS_Util");
    
    internal ConsoleApplication1_ACS_UtilAccessor(object target) : 
            base(target, m_privateType) {
    }
    
    internal global::System.DateTime dt_Fecha {
        get {
            global::System.DateTime ret = ((global::System.DateTime)(m_privateObject.GetField("dt_Fecha")));
            return ret;
        }
        set {
            m_privateObject.SetField("dt_Fecha", value);
        }
    }
    
    internal void EscribirMensaje(string strMensaje) {
        object[] args = new object[] {
                strMensaje};
        m_privateObject.Invoke("EscribirMensaje", new System.Type[] {
                    typeof(string)}, args);
    }
    
    internal string GenerarFormato(int intValor) {
        object[] args = new object[] {
                intValor};
        string ret = ((string)(m_privateObject.Invoke("GenerarFormato", new System.Type[] {
                    typeof(int)}, args)));
        return ret;
    }
    
    internal string ObtenerCodCompania(string strAirlineDesign, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.Compania> lstCompania) {
        object[] args = new object[] {
                strAirlineDesign,
                lstCompania};
        string ret = ((string)(m_privateObject.Invoke("ObtenerCodCompania", new System.Type[] {
                    typeof(string),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.Compania>)}, args)));
        return ret;
    }
    
    internal string ObtenerTipoError(string strTipoError, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo> Lst_ListaDeCampo) {
        object[] args = new object[] {
                strTipoError,
                Lst_ListaDeCampo};
        string ret = ((string)(m_privateObject.Invoke("ObtenerTipoError", new System.Type[] {
                    typeof(string),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo>)}, args)));
        return ret;
    }
    
    internal global::System.DateTime ObtenerFecha(int julianDate) {
        object[] args = new object[] {
                julianDate};
        global::System.DateTime ret = ((global::System.DateTime)(m_privateObject.Invoke("ObtenerFecha", new System.Type[] {
                    typeof(int)}, args)));
        return ret;
    }
    
    internal static object CreatePrivate() {
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("ACCESOS", "ConsoleApplication1.ACS_Util", new object[0]);
        return priv_obj.Target;
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class LAP_TUUA_ACCESOS_ACS_BoardingAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "LAP.TUUA.ACCESOS.ACS_Boarding");
    
    internal LAP_TUUA_ACCESOS_ACS_BoardingAccessor(object target) : 
            base(target, m_privateType) {
    }
    
    internal global::System.Collections.Hashtable Ht_Boarding {
        get {
            global::System.Collections.Hashtable ret = ((global::System.Collections.Hashtable)(m_privateObject.GetField("Ht_Boarding")));
            return ret;
        }
        set {
            m_privateObject.SetField("Ht_Boarding", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_BoardingBcbp Obj_DAOBoardingBcbp {
        get {
            global::LAP.TUUA.DAO.DAO_BoardingBcbp ret = ((global::LAP.TUUA.DAO.DAO_BoardingBcbp)(m_privateObject.GetField("Obj_DAOBoardingBcbp")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOBoardingBcbp", value);
        }
    }
    
    internal global::LAP.TUUA.ENTIDADES.BoardingBcbpErr Obj_BoardingBcbpErr {
        get {
            global::LAP.TUUA.ENTIDADES.BoardingBcbpErr ret = ((global::LAP.TUUA.ENTIDADES.BoardingBcbpErr)(m_privateObject.GetField("Obj_BoardingBcbpErr")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_BoardingBcbpErr", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_BoardingBcbpErr Obj_DAOBoardingBcbpErr {
        get {
            global::LAP.TUUA.DAO.DAO_BoardingBcbpErr ret = ((global::LAP.TUUA.DAO.DAO_BoardingBcbpErr)(m_privateObject.GetField("Obj_DAOBoardingBcbpErr")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOBoardingBcbpErr", value);
        }
    }
    
    internal global::TestAccesos.LAP_TUUA_ACCESOS_ACS_InterfazPinPadAccessor Obj_IntzPinPad {
        get {
            object _ret_val = m_privateObject.GetField("Obj_IntzPinPad");
            global::TestAccesos.LAP_TUUA_ACCESOS_ACS_InterfazPinPadAccessor _ret = null;
            if ((_ret_val != null)) {
                _ret = new global::TestAccesos.LAP_TUUA_ACCESOS_ACS_InterfazPinPadAccessor(_ret_val);
            }
            global::TestAccesos.LAP_TUUA_ACCESOS_ACS_InterfazPinPadAccessor ret = _ret;
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_IntzPinPad", value);
        }
    }
    
    internal global::TestAccesos.LAP_TUUA_ACCESOS_ACS_UtilAccessor Obj_Util {
        get {
            object _ret_val = m_privateObject.GetField("Obj_Util");
            global::TestAccesos.LAP_TUUA_ACCESOS_ACS_UtilAccessor _ret = null;
            if ((_ret_val != null)) {
                _ret = new global::TestAccesos.LAP_TUUA_ACCESOS_ACS_UtilAccessor(_ret_val);
            }
            global::TestAccesos.LAP_TUUA_ACCESOS_ACS_UtilAccessor ret = _ret;
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_Util", value);
        }
    }
    
    internal int estado {
        get {
            int ret = ((int)(m_privateObject.GetField("estado")));
            return ret;
        }
        set {
            m_privateObject.SetField("estado", value);
        }
    }
    
    internal global::LAP.TUUA.ACCESOS.Semaforo formSemaforo {
        get {
            global::LAP.TUUA.ACCESOS.Semaforo ret = ((global::LAP.TUUA.ACCESOS.Semaforo)(m_privateObject.GetField("formSemaforo")));
            return ret;
        }
        set {
            m_privateObject.SetField("formSemaforo", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_ModVentaComp Obj_DAOModVentaComp {
        get {
            global::LAP.TUUA.DAO.DAO_ModVentaComp ret = ((global::LAP.TUUA.DAO.DAO_ModVentaComp)(m_privateObject.GetField("Obj_DAOModVentaComp")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOModVentaComp", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_VueloProgramado Obj_DAOVueloProgramado {
        get {
            global::LAP.TUUA.DAO.DAO_VueloProgramado ret = ((global::LAP.TUUA.DAO.DAO_VueloProgramado)(m_privateObject.GetField("Obj_DAOVueloProgramado")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOVueloProgramado", value);
        }
    }
    
    internal static object CreatePrivate(global::System.Collections.Hashtable htBoarding, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.Compania> Lst_Compania, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo> Lst_ListaDeCampo, global::TestAccesos.LAP_TUUA_ACCESOS_ACS_InterfazPinPadAccessor Obj_IntzPinPad) {
        object Obj_IntzPinPad_val_target = null;
        if ((Obj_IntzPinPad != null)) {
            Obj_IntzPinPad_val_target = Obj_IntzPinPad.Target;
        }
        object[] args = new object[] {
                htBoarding,
                Lst_Compania,
                Lst_ListaDeCampo,
                Obj_IntzPinPad_val_target};
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType target = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "LAP.TUUA.ACCESOS.ACS_InterfazPinPad");
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("ACCESOS", "LAP.TUUA.ACCESOS.ACS_Boarding", new System.Type[] {
                    typeof(global::System.Collections.Hashtable),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.Compania>),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo>),
                    target.ReferencedType}, args);
        return priv_obj.Target;
    }
    
    internal void ValidarBCBP(global::LAP.TUUA.ENTIDADES.BoardingBcbp Obj_BoardingBcbp, string strTrama) {
        object[] args = new object[] {
                Obj_BoardingBcbp,
                strTrama};
        m_privateObject.Invoke("ValidarBCBP", new System.Type[] {
                    typeof(global::LAP.TUUA.ENTIDADES.BoardingBcbp),
                    typeof(string)}, args);
    }
    
    internal void MostrarError(string strTrama, string strTipoError, string strMsg) {
        object[] args = new object[] {
                strTrama,
                strTipoError,
                strMsg};
        m_privateObject.Invoke("MostrarError", new System.Type[] {
                    typeof(string),
                    typeof(string),
                    typeof(string)}, args);
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class LAP_TUUA_ACCESOS_ACS_InterfazPinPadAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "LAP.TUUA.ACCESOS.ACS_InterfazPinPad");
    
    internal LAP_TUUA_ACCESOS_ACS_InterfazPinPadAccessor(object target) : 
            base(target, m_privateType) {
    }
    
    internal global::System.Threading.Thread obj_HiloInterfazPinpad {
        get {
            global::System.Threading.Thread ret = ((global::System.Threading.Thread)(m_privateObject.GetField("obj_HiloInterfazPinpad")));
            return ret;
        }
        set {
            m_privateObject.SetField("obj_HiloInterfazPinpad", value);
        }
    }
    
    internal global::TestAccesos.LAP_TUUA_ACCESOS_ACS_SincronizaLecturaAccessor Obj_SincPinPad {
        get {
            object _ret_val = m_privateObject.GetField("Obj_SincPinPad");
            global::TestAccesos.LAP_TUUA_ACCESOS_ACS_SincronizaLecturaAccessor _ret = null;
            if ((_ret_val != null)) {
                _ret = new global::TestAccesos.LAP_TUUA_ACCESOS_ACS_SincronizaLecturaAccessor(_ret_val);
            }
            global::TestAccesos.LAP_TUUA_ACCESOS_ACS_SincronizaLecturaAccessor ret = _ret;
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_SincPinPad", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_Usuario Obj_DAOUsuario {
        get {
            global::LAP.TUUA.DAO.DAO_Usuario ret = ((global::LAP.TUUA.DAO.DAO_Usuario)(m_privateObject.GetField("Obj_DAOUsuario")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOUsuario", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_Ticket Obj_DAOTicket {
        get {
            global::LAP.TUUA.DAO.DAO_Ticket ret = ((global::LAP.TUUA.DAO.DAO_Ticket)(m_privateObject.GetField("Obj_DAOTicket")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOTicket", value);
        }
    }
    
    internal global::LAP.TUUA.DAO.DAO_BoardingBcbp Obj_DAOBoardingBcbp {
        get {
            global::LAP.TUUA.DAO.DAO_BoardingBcbp ret = ((global::LAP.TUUA.DAO.DAO_BoardingBcbp)(m_privateObject.GetField("Obj_DAOBoardingBcbp")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_DAOBoardingBcbp", value);
        }
    }
    
    internal global::LAP.TUUA.ENTIDADES.Ticket Obj_Ticket {
        get {
            global::LAP.TUUA.ENTIDADES.Ticket ret = ((global::LAP.TUUA.ENTIDADES.Ticket)(m_privateObject.GetField("Obj_Ticket")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_Ticket", value);
        }
    }
    
    internal global::LAP.TUUA.ENTIDADES.Usuario Obj_Usuario {
        get {
            global::LAP.TUUA.ENTIDADES.Usuario ret = ((global::LAP.TUUA.ENTIDADES.Usuario)(m_privateObject.GetField("Obj_Usuario")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_Usuario", value);
        }
    }
    
    internal global::LAP.TUUA.ENTIDADES.BoardingBcbp Obj_BoardingBcbp {
        get {
            global::LAP.TUUA.ENTIDADES.BoardingBcbp ret = ((global::LAP.TUUA.ENTIDADES.BoardingBcbp)(m_privateObject.GetField("Obj_BoardingBcbp")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_BoardingBcbp", value);
        }
    }
    
    internal global::HCOMHEPSLib.CajaClass Obj_PinPad {
        get {
            global::HCOMHEPSLib.CajaClass ret = ((global::HCOMHEPSLib.CajaClass)(m_privateObject.GetField("Obj_PinPad")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_PinPad", value);
        }
    }
    
    internal global::System.DateTime dt_Fecha {
        get {
            global::System.DateTime ret = ((global::System.DateTime)(m_privateObject.GetField("dt_Fecha")));
            return ret;
        }
        set {
            m_privateObject.SetField("dt_Fecha", value);
        }
    }
    
    internal global::TestAccesos.LAP_TUUA_ACCESOS_ACS_UtilAccessor Obj_Util {
        get {
            object _ret_val = m_privateObject.GetField("Obj_Util");
            global::TestAccesos.LAP_TUUA_ACCESOS_ACS_UtilAccessor _ret = null;
            if ((_ret_val != null)) {
                _ret = new global::TestAccesos.LAP_TUUA_ACCESOS_ACS_UtilAccessor(_ret_val);
            }
            global::TestAccesos.LAP_TUUA_ACCESOS_ACS_UtilAccessor ret = _ret;
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_Util", value);
        }
    }
    
    internal global::LAP.TUUA.ACCESOS.Semaforo frmSemaforo {
        get {
            global::LAP.TUUA.ACCESOS.Semaforo ret = ((global::LAP.TUUA.ACCESOS.Semaforo)(m_privateObject.GetField("frmSemaforo")));
            return ret;
        }
        set {
            m_privateObject.SetField("frmSemaforo", value);
        }
    }
    
    internal int estado {
        get {
            int ret = ((int)(m_privateObject.GetField("estado")));
            return ret;
        }
        set {
            m_privateObject.SetField("estado", value);
        }
    }
    
    internal global::ATLCOMLib.Comm Obj_LectorCB {
        get {
            global::ATLCOMLib.Comm ret = ((global::ATLCOMLib.Comm)(m_privateObject.GetField("Obj_LectorCB")));
            return ret;
        }
        set {
            m_privateObject.SetField("Obj_LectorCB", value);
        }
    }
    
    internal static object CreatePrivate(global::TestAccesos.LAP_TUUA_ACCESOS_ACS_SincronizaLecturaAccessor Obj_Sinc, global::HCOMHEPSLib.CajaClass Obj_PinPad, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.Compania> Lst_Compania, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo> Lst_ListaDeCampo, global::LAP.TUUA.ACCESOS.Semaforo frmSemaforo, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.TipoTicket> Lst_TipoTicket, global::ATLCOMLib.Comm Obj_LectorCB) {
        object Obj_Sinc_val_target = null;
        if ((Obj_Sinc != null)) {
            Obj_Sinc_val_target = Obj_Sinc.Target;
        }
        object[] args = new object[] {
                Obj_Sinc_val_target,
                Obj_PinPad,
                Lst_Compania,
                Lst_ListaDeCampo,
                frmSemaforo,
                Lst_TipoTicket,
                Obj_LectorCB};
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType target = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "LAP.TUUA.ACCESOS.ACS_SincronizaLectura");
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("ACCESOS", "LAP.TUUA.ACCESOS.ACS_InterfazPinPad", new System.Type[] {
                    target.ReferencedType,
                    typeof(global::HCOMHEPSLib.CajaClass),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.Compania>),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo>),
                    typeof(global::LAP.TUUA.ACCESOS.Semaforo),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.TipoTicket>),
                    typeof(global::ATLCOMLib.Comm)}, args);
        return priv_obj.Target;
    }
    
    internal void Ejecutar() {
        object[] args = new object[0];
        m_privateObject.Invoke("Ejecutar", new System.Type[0], args);
    }
    
    internal int EnviarTransPinPad(string strCodTransaccion, string strMsgTrans) {
        object[] args = new object[] {
                strCodTransaccion,
                strMsgTrans};
        int ret = ((int)(m_privateObject.Invoke("EnviarTransPinPad", new System.Type[] {
                    typeof(string),
                    typeof(string)}, args)));
        return ret;
    }
    
    internal void ProcesarBoarding(string strMessage) {
        object[] args = new object[] {
                strMessage};
        m_privateObject.Invoke("ProcesarBoarding", new System.Type[] {
                    typeof(string)}, args);
    }
    
    internal void ProcesarTicket(string strNumTicket, string strMessage) {
        object[] args = new object[] {
                strNumTicket,
                strMessage};
        m_privateObject.Invoke("ProcesarTicket", new System.Type[] {
                    typeof(string),
                    typeof(string)}, args);
    }
    
    internal void LeerPinPad() {
        object[] args = new object[0];
        m_privateObject.Invoke("LeerPinPad", new System.Type[0], args);
    }
    
    internal int MostrarMsgPINPad(string strCodTransaccion, string strMsgDataAdicional, string strMsgDataTrack2) {
        object[] args = new object[] {
                strCodTransaccion,
                strMsgDataAdicional,
                strMsgDataTrack2};
        int ret = ((int)(m_privateObject.Invoke("MostrarMsgPINPad", new System.Type[] {
                    typeof(string),
                    typeof(string),
                    typeof(string)}, args)));
        return ret;
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class LAP_TUUA_ACCESOS_ACS_SincronizaLecturaAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "LAP.TUUA.ACCESOS.ACS_SincronizaLectura");
    
    internal LAP_TUUA_ACCESOS_ACS_SincronizaLecturaAccessor(object target) : 
            base(target, m_privateType) {
    }
    
    internal bool flg_LecturaScaner {
        get {
            bool ret = ((bool)(m_privateObject.GetField("flg_LecturaScaner")));
            return ret;
        }
        set {
            m_privateObject.SetField("flg_LecturaScaner", value);
        }
    }
    
    internal static object CreatePrivate() {
        object[] args = new object[0];
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("ACCESOS", "LAP.TUUA.ACCESOS.ACS_SincronizaLectura", new System.Type[0], args);
        return priv_obj.Target;
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class LAP_TUUA_ACCESOS_ACS_UtilAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("ACCESOS", "LAP.TUUA.ACCESOS.ACS_Util");
    
    internal LAP_TUUA_ACCESOS_ACS_UtilAccessor(object target) : 
            base(target, m_privateType) {
    }
    
    internal global::System.DateTime dt_Fecha {
        get {
            global::System.DateTime ret = ((global::System.DateTime)(m_privateObject.GetField("dt_Fecha")));
            return ret;
        }
        set {
            m_privateObject.SetField("dt_Fecha", value);
        }
    }
    
    internal string ObtenerTicket(string strTrama) {
        object[] args = new object[] {
                strTrama};
        string ret = ((string)(m_privateObject.Invoke("ObtenerTicket", new System.Type[] {
                    typeof(string)}, args)));
        return ret;
    }
    
    internal void EscribirLog(object objClase, string strMensaje) {
        object[] args = new object[] {
                objClase,
                strMensaje};
        m_privateObject.Invoke("EscribirLog", new System.Type[] {
                    typeof(object),
                    typeof(string)}, args);
    }
    
    internal void EscribirMensaje(string strMensaje) {
        object[] args = new object[] {
                strMensaje};
        m_privateObject.Invoke("EscribirMensaje", new System.Type[] {
                    typeof(string)}, args);
    }
    
    internal string GenerarFormato(int intValor) {
        object[] args = new object[] {
                intValor};
        string ret = ((string)(m_privateObject.Invoke("GenerarFormato", new System.Type[] {
                    typeof(int)}, args)));
        return ret;
    }
    
    internal string ObtenerCodCompania(string strAirlineDesign, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.Compania> lstCompania) {
        object[] args = new object[] {
                strAirlineDesign,
                lstCompania};
        string ret = ((string)(m_privateObject.Invoke("ObtenerCodCompania", new System.Type[] {
                    typeof(string),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.Compania>)}, args)));
        return ret;
    }
    
    internal string ObtenerTipoPasajero(string strCodTipTicket, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.TipoTicket> Lst_TipoTicket) {
        object[] args = new object[] {
                strCodTipTicket,
                Lst_TipoTicket};
        string ret = ((string)(m_privateObject.Invoke("ObtenerTipoPasajero", new System.Type[] {
                    typeof(string),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.TipoTicket>)}, args)));
        return ret;
    }
    
    internal string ObtenerEstadoTicket(string strTipEstado, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo> Lst_ListaDeCampo) {
        object[] args = new object[] {
                strTipEstado,
                Lst_ListaDeCampo};
        string ret = ((string)(m_privateObject.Invoke("ObtenerEstadoTicket", new System.Type[] {
                    typeof(string),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo>)}, args)));
        return ret;
    }
    
    internal string ObtenerTipoError(string strTipoError, System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo> Lst_ListaDeCampo) {
        object[] args = new object[] {
                strTipoError,
                Lst_ListaDeCampo};
        string ret = ((string)(m_privateObject.Invoke("ObtenerTipoError", new System.Type[] {
                    typeof(string),
                    typeof(System.Collections.Generic.List<LAP.TUUA.ENTIDADES.ListaDeCampo>)}, args)));
        return ret;
    }
    
    internal string GenerarDetalleTicket(global::LAP.TUUA.ENTIDADES.Ticket objTicket) {
        object[] args = new object[] {
                objTicket};
        string ret = ((string)(m_privateObject.Invoke("GenerarDetalleTicket", new System.Type[] {
                    typeof(global::LAP.TUUA.ENTIDADES.Ticket)}, args)));
        return ret;
    }
    
    internal string InvertirFecha(string strFecha) {
        object[] args = new object[] {
                strFecha};
        string ret = ((string)(m_privateObject.Invoke("InvertirFecha", new System.Type[] {
                    typeof(string)}, args)));
        return ret;
    }
    
    internal string ConvertirDosDigitos(int intValor) {
        object[] args = new object[] {
                intValor};
        string ret = ((string)(m_privateObject.Invoke("ConvertirDosDigitos", new System.Type[] {
                    typeof(int)}, args)));
        return ret;
    }
    
    internal string GenerarDetalleBoarding(global::LAP.TUUA.ENTIDADES.BoardingBcbp objBoarding) {
        object[] args = new object[] {
                objBoarding};
        string ret = ((string)(m_privateObject.Invoke("GenerarDetalleBoarding", new System.Type[] {
                    typeof(global::LAP.TUUA.ENTIDADES.BoardingBcbp)}, args)));
        return ret;
    }
    
    internal string ObtenerFecha() {
        object[] args = new object[0];
        string ret = ((string)(m_privateObject.Invoke("ObtenerFecha", new System.Type[0], args)));
        return ret;
    }
    
    internal string ObtenerHora() {
        object[] args = new object[0];
        string ret = ((string)(m_privateObject.Invoke("ObtenerHora", new System.Type[0], args)));
        return ret;
    }
    
    internal string ConvertirJulianoCalendario(int jd) {
        object[] args = new object[] {
                jd};
        string ret = ((string)(m_privateObject.Invoke("ConvertirJulianoCalendario", new System.Type[] {
                    typeof(int)}, args)));
        return ret;
    }
    
    internal static object CreatePrivate() {
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("ACCESOS", "LAP.TUUA.ACCESOS.ACS_Util", new object[0]);
        return priv_obj.Target;
    }
}
}
