USE [BD_TUUA_PRD]
GO
BEGIN TRANSACTION
	CREATE PARTITION FUNCTION [PF_TUA_Ticket](char(16)) AS RANGE LEFT FOR VALUES (N'9000600303949820', N'9000600308442050')

	CREATE PARTITION SCHEME [PS_TUA_Ticket] AS PARTITION [PF_TUA_Ticket] TO ([BD_TUUA_PRD_2010], [BD_TUUA_PRD_2011], [PRIMARY])

	CREATE CLUSTERED INDEX [IDX_ESTADO_TICKET] ON [dbo].[TUA_Ticket]
	(
		[Tip_Estado_Actual] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_TUA_Ticket]([Cod_Numero_Ticket])

COMMIT TRANSACTION



