USE [BD_TUUA_PRD]
GO
BEGIN TRANSACTION
	CREATE PARTITION FUNCTION [PF_TUA_BoardingBcbpEstHist](bigint) AS RANGE LEFT FOR VALUES (N'3535926')

	CREATE PARTITION SCHEME [PS_TUA_BoardingBcbpEstHist] AS PARTITION [PF_TUA_BoardingBcbpEstHist] TO ([BD_TUUA_PRD_2011], [PRIMARY])

	ALTER TABLE [dbo].[TUA_BoardingBcbpEstHist] DROP CONSTRAINT [PK_TUA_BoardingBcbpEstHist_1]

	ALTER TABLE [dbo].[TUA_BoardingBcbpEstHist] ADD  CONSTRAINT [PK_TUA_BoardingBcbpEstHist_1] PRIMARY KEY CLUSTERED 
	(
		[Num_Secuencial_Bcbp] ASC,
		[Num_Secuencial] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_TUA_BoardingBcbpEstHist]([Num_Secuencial_Bcbp])

COMMIT TRANSACTION



