USE [BD_TUUA_PRD]
GO
BEGIN TRANSACTION
	CREATE PARTITION FUNCTION [PF_TUA_BoardingBcbpErr](bigint) AS RANGE LEFT FOR VALUES (N'3535926')

	CREATE PARTITION SCHEME [PS_TUA_BoardingBcbpErr] AS PARTITION [PF_TUA_BoardingBcbpErr] TO ([BD_TUUA_PRD_2011], [PRIMARY])

	CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_TUA_BoardingBcbpErr_636207688908605338] ON [dbo].[TUA_BoardingBcbpErr]
	(
		[Num_Secuencial]
	)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_TUA_BoardingBcbpErr]([Num_Secuencial])

	DROP INDEX [ClusteredIndex_on_PS_TUA_BoardingBcbpErr_636207688908605338] ON [dbo].[TUA_BoardingBcbpErr]

	ALTER TABLE [dbo].[TUA_BoardingBcbpErr] DROP CONSTRAINT [PK_BoardingBcbpError]

	ALTER TABLE [dbo].[TUA_BoardingBcbpErr] ADD  CONSTRAINT [PK_BoardingBcbpError] PRIMARY KEY NONCLUSTERED 
	(
		[Num_Secuencial] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_TUA_BoardingBcbpErr]([Num_Secuencial])

COMMIT TRANSACTION



