//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LAP.TUUA.CLIENTEWS.WSRehabilitacion {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSRehabilitacionSoap", Namespace="http://tempuri.org/")]
    public partial class WSRehabilitacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarRepresXRehabilitacionYCiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarRehabilitacionTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarVuelosTicketPorCiaFechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarTicketsPorVueloOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarVuelosBCBPPorCiaFechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarRehabilitacionBCBPOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarRehabilitacionBCBPAmpliacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarCompania_xCodigoEspecialOperationCompleted;
        
        private System.Threading.SendOrPostCallback obteneterBoardingsByRangoFechasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSRehabilitacion() {
            this.Url = global::LAP.TUUA.CLIENTEWS.Properties.Settings.Default.CLIENTEWS_WSRehabilitacion_WSRehabilitacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarRepresXRehabilitacionYCiaCompletedEventHandler ConsultarRepresXRehabilitacionYCiaCompleted;
        
        /// <remarks/>
        public event registrarRehabilitacionTicketCompletedEventHandler registrarRehabilitacionTicketCompleted;
        
        /// <remarks/>
        public event consultarVuelosTicketPorCiaFechaCompletedEventHandler consultarVuelosTicketPorCiaFechaCompleted;
        
        /// <remarks/>
        public event consultarTicketsPorVueloCompletedEventHandler consultarTicketsPorVueloCompleted;
        
        /// <remarks/>
        public event consultarVuelosBCBPPorCiaFechaCompletedEventHandler consultarVuelosBCBPPorCiaFechaCompleted;
        
        /// <remarks/>
        public event registrarRehabilitacionBCBPCompletedEventHandler registrarRehabilitacionBCBPCompleted;
        
        /// <remarks/>
        public event registrarRehabilitacionBCBPAmpliacionCompletedEventHandler registrarRehabilitacionBCBPAmpliacionCompleted;
        
        /// <remarks/>
        public event listarCompania_xCodigoEspecialCompletedEventHandler listarCompania_xCodigoEspecialCompleted;
        
        /// <remarks/>
        public event obteneterBoardingsByRangoFechasCompletedEventHandler obteneterBoardingsByRangoFechasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarRepresXRehabilitacionYCia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultarRepresXRehabilitacionYCia(string strCia) {
            object[] results = this.Invoke("ConsultarRepresXRehabilitacionYCia", new object[] {
                        strCia});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarRepresXRehabilitacionYCiaAsync(string strCia) {
            this.ConsultarRepresXRehabilitacionYCiaAsync(strCia, null);
        }
        
        /// <remarks/>
        public void ConsultarRepresXRehabilitacionYCiaAsync(string strCia, object userState) {
            if ((this.ConsultarRepresXRehabilitacionYCiaOperationCompleted == null)) {
                this.ConsultarRepresXRehabilitacionYCiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarRepresXRehabilitacionYCiaOperationCompleted);
            }
            this.InvokeAsync("ConsultarRepresXRehabilitacionYCia", new object[] {
                        strCia}, this.ConsultarRepresXRehabilitacionYCiaOperationCompleted, userState);
        }
        
        private void OnConsultarRepresXRehabilitacionYCiaOperationCompleted(object arg) {
            if ((this.ConsultarRepresXRehabilitacionYCiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarRepresXRehabilitacionYCiaCompleted(this, new ConsultarRepresXRehabilitacionYCiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarRehabilitacionTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool registrarRehabilitacionTicket(ref TicketEstHist objTicketEstHist, int flag, int sizeOutput) {
            object[] results = this.Invoke("registrarRehabilitacionTicket", new object[] {
                        objTicketEstHist,
                        flag,
                        sizeOutput});
            objTicketEstHist = ((TicketEstHist)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void registrarRehabilitacionTicketAsync(TicketEstHist objTicketEstHist, int flag, int sizeOutput) {
            this.registrarRehabilitacionTicketAsync(objTicketEstHist, flag, sizeOutput, null);
        }
        
        /// <remarks/>
        public void registrarRehabilitacionTicketAsync(TicketEstHist objTicketEstHist, int flag, int sizeOutput, object userState) {
            if ((this.registrarRehabilitacionTicketOperationCompleted == null)) {
                this.registrarRehabilitacionTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarRehabilitacionTicketOperationCompleted);
            }
            this.InvokeAsync("registrarRehabilitacionTicket", new object[] {
                        objTicketEstHist,
                        flag,
                        sizeOutput}, this.registrarRehabilitacionTicketOperationCompleted, userState);
        }
        
        private void OnregistrarRehabilitacionTicketOperationCompleted(object arg) {
            if ((this.registrarRehabilitacionTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarRehabilitacionTicketCompleted(this, new registrarRehabilitacionTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarVuelosTicketPorCiaFecha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable consultarVuelosTicketPorCiaFecha(string sCompania, string fechaVuelo) {
            object[] results = this.Invoke("consultarVuelosTicketPorCiaFecha", new object[] {
                        sCompania,
                        fechaVuelo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void consultarVuelosTicketPorCiaFechaAsync(string sCompania, string fechaVuelo) {
            this.consultarVuelosTicketPorCiaFechaAsync(sCompania, fechaVuelo, null);
        }
        
        /// <remarks/>
        public void consultarVuelosTicketPorCiaFechaAsync(string sCompania, string fechaVuelo, object userState) {
            if ((this.consultarVuelosTicketPorCiaFechaOperationCompleted == null)) {
                this.consultarVuelosTicketPorCiaFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarVuelosTicketPorCiaFechaOperationCompleted);
            }
            this.InvokeAsync("consultarVuelosTicketPorCiaFecha", new object[] {
                        sCompania,
                        fechaVuelo}, this.consultarVuelosTicketPorCiaFechaOperationCompleted, userState);
        }
        
        private void OnconsultarVuelosTicketPorCiaFechaOperationCompleted(object arg) {
            if ((this.consultarVuelosTicketPorCiaFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarVuelosTicketPorCiaFechaCompleted(this, new consultarVuelosTicketPorCiaFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarTicketsPorVuelo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable consultarTicketsPorVuelo(string sCompania, string fechaVuelo, string dsc_Num_Vuelo) {
            object[] results = this.Invoke("consultarTicketsPorVuelo", new object[] {
                        sCompania,
                        fechaVuelo,
                        dsc_Num_Vuelo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void consultarTicketsPorVueloAsync(string sCompania, string fechaVuelo, string dsc_Num_Vuelo) {
            this.consultarTicketsPorVueloAsync(sCompania, fechaVuelo, dsc_Num_Vuelo, null);
        }
        
        /// <remarks/>
        public void consultarTicketsPorVueloAsync(string sCompania, string fechaVuelo, string dsc_Num_Vuelo, object userState) {
            if ((this.consultarTicketsPorVueloOperationCompleted == null)) {
                this.consultarTicketsPorVueloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarTicketsPorVueloOperationCompleted);
            }
            this.InvokeAsync("consultarTicketsPorVuelo", new object[] {
                        sCompania,
                        fechaVuelo,
                        dsc_Num_Vuelo}, this.consultarTicketsPorVueloOperationCompleted, userState);
        }
        
        private void OnconsultarTicketsPorVueloOperationCompleted(object arg) {
            if ((this.consultarTicketsPorVueloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarTicketsPorVueloCompleted(this, new consultarTicketsPorVueloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarVuelosBCBPPorCiaFecha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable consultarVuelosBCBPPorCiaFecha(string sCompania, string fechaVuelo) {
            object[] results = this.Invoke("consultarVuelosBCBPPorCiaFecha", new object[] {
                        sCompania,
                        fechaVuelo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void consultarVuelosBCBPPorCiaFechaAsync(string sCompania, string fechaVuelo) {
            this.consultarVuelosBCBPPorCiaFechaAsync(sCompania, fechaVuelo, null);
        }
        
        /// <remarks/>
        public void consultarVuelosBCBPPorCiaFechaAsync(string sCompania, string fechaVuelo, object userState) {
            if ((this.consultarVuelosBCBPPorCiaFechaOperationCompleted == null)) {
                this.consultarVuelosBCBPPorCiaFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarVuelosBCBPPorCiaFechaOperationCompleted);
            }
            this.InvokeAsync("consultarVuelosBCBPPorCiaFecha", new object[] {
                        sCompania,
                        fechaVuelo}, this.consultarVuelosBCBPPorCiaFechaOperationCompleted, userState);
        }
        
        private void OnconsultarVuelosBCBPPorCiaFechaOperationCompleted(object arg) {
            if ((this.consultarVuelosBCBPPorCiaFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarVuelosBCBPPorCiaFechaCompleted(this, new consultarVuelosBCBPPorCiaFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarRehabilitacionBCBP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool registrarRehabilitacionBCBP(ref BoardingBcbpEstHist boardingBcbpEstHist, int flag, int sizeOutput) {
            object[] results = this.Invoke("registrarRehabilitacionBCBP", new object[] {
                        boardingBcbpEstHist,
                        flag,
                        sizeOutput});
            boardingBcbpEstHist = ((BoardingBcbpEstHist)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void registrarRehabilitacionBCBPAsync(BoardingBcbpEstHist boardingBcbpEstHist, int flag, int sizeOutput) {
            this.registrarRehabilitacionBCBPAsync(boardingBcbpEstHist, flag, sizeOutput, null);
        }
        
        /// <remarks/>
        public void registrarRehabilitacionBCBPAsync(BoardingBcbpEstHist boardingBcbpEstHist, int flag, int sizeOutput, object userState) {
            if ((this.registrarRehabilitacionBCBPOperationCompleted == null)) {
                this.registrarRehabilitacionBCBPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarRehabilitacionBCBPOperationCompleted);
            }
            this.InvokeAsync("registrarRehabilitacionBCBP", new object[] {
                        boardingBcbpEstHist,
                        flag,
                        sizeOutput}, this.registrarRehabilitacionBCBPOperationCompleted, userState);
        }
        
        private void OnregistrarRehabilitacionBCBPOperationCompleted(object arg) {
            if ((this.registrarRehabilitacionBCBPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarRehabilitacionBCBPCompleted(this, new registrarRehabilitacionBCBPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarRehabilitacionBCBPAmpliacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool registrarRehabilitacionBCBPAmpliacion(ref BoardingBcbpEstHist boardingBcbpEstHist, int flag, int sizeOutput) {
            object[] results = this.Invoke("registrarRehabilitacionBCBPAmpliacion", new object[] {
                        boardingBcbpEstHist,
                        flag,
                        sizeOutput});
            boardingBcbpEstHist = ((BoardingBcbpEstHist)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void registrarRehabilitacionBCBPAmpliacionAsync(BoardingBcbpEstHist boardingBcbpEstHist, int flag, int sizeOutput) {
            this.registrarRehabilitacionBCBPAmpliacionAsync(boardingBcbpEstHist, flag, sizeOutput, null);
        }
        
        /// <remarks/>
        public void registrarRehabilitacionBCBPAmpliacionAsync(BoardingBcbpEstHist boardingBcbpEstHist, int flag, int sizeOutput, object userState) {
            if ((this.registrarRehabilitacionBCBPAmpliacionOperationCompleted == null)) {
                this.registrarRehabilitacionBCBPAmpliacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarRehabilitacionBCBPAmpliacionOperationCompleted);
            }
            this.InvokeAsync("registrarRehabilitacionBCBPAmpliacion", new object[] {
                        boardingBcbpEstHist,
                        flag,
                        sizeOutput}, this.registrarRehabilitacionBCBPAmpliacionOperationCompleted, userState);
        }
        
        private void OnregistrarRehabilitacionBCBPAmpliacionOperationCompleted(object arg) {
            if ((this.registrarRehabilitacionBCBPAmpliacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarRehabilitacionBCBPAmpliacionCompleted(this, new registrarRehabilitacionBCBPAmpliacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarCompania_xCodigoEspecial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable listarCompania_xCodigoEspecial(string codigoEspecial) {
            object[] results = this.Invoke("listarCompania_xCodigoEspecial", new object[] {
                        codigoEspecial});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void listarCompania_xCodigoEspecialAsync(string codigoEspecial) {
            this.listarCompania_xCodigoEspecialAsync(codigoEspecial, null);
        }
        
        /// <remarks/>
        public void listarCompania_xCodigoEspecialAsync(string codigoEspecial, object userState) {
            if ((this.listarCompania_xCodigoEspecialOperationCompleted == null)) {
                this.listarCompania_xCodigoEspecialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarCompania_xCodigoEspecialOperationCompleted);
            }
            this.InvokeAsync("listarCompania_xCodigoEspecial", new object[] {
                        codigoEspecial}, this.listarCompania_xCodigoEspecialOperationCompleted, userState);
        }
        
        private void OnlistarCompania_xCodigoEspecialOperationCompleted(object arg) {
            if ((this.listarCompania_xCodigoEspecialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarCompania_xCodigoEspecialCompleted(this, new listarCompania_xCodigoEspecialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obteneterBoardingsByRangoFechas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable obteneterBoardingsByRangoFechas(string sCompania, string sFchDesde, string sFchHasta, string sHoraDesde, string sHoraHasta) {
            object[] results = this.Invoke("obteneterBoardingsByRangoFechas", new object[] {
                        sCompania,
                        sFchDesde,
                        sFchHasta,
                        sHoraDesde,
                        sHoraHasta});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void obteneterBoardingsByRangoFechasAsync(string sCompania, string sFchDesde, string sFchHasta, string sHoraDesde, string sHoraHasta) {
            this.obteneterBoardingsByRangoFechasAsync(sCompania, sFchDesde, sFchHasta, sHoraDesde, sHoraHasta, null);
        }
        
        /// <remarks/>
        public void obteneterBoardingsByRangoFechasAsync(string sCompania, string sFchDesde, string sFchHasta, string sHoraDesde, string sHoraHasta, object userState) {
            if ((this.obteneterBoardingsByRangoFechasOperationCompleted == null)) {
                this.obteneterBoardingsByRangoFechasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobteneterBoardingsByRangoFechasOperationCompleted);
            }
            this.InvokeAsync("obteneterBoardingsByRangoFechas", new object[] {
                        sCompania,
                        sFchDesde,
                        sFchHasta,
                        sHoraDesde,
                        sHoraHasta}, this.obteneterBoardingsByRangoFechasOperationCompleted, userState);
        }
        
        private void OnobteneterBoardingsByRangoFechasOperationCompleted(object arg) {
            if ((this.obteneterBoardingsByRangoFechasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obteneterBoardingsByRangoFechasCompleted(this, new obteneterBoardingsByRangoFechasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TicketEstHist {
        
        private string sCodNumeroTicketField;
        
        private string sTipEstadoField;
        
        private string sDscTicketEstadoField;
        
        private string sCodEquipoModField;
        
        private string sDscNumVueloField;
        
        private string sLogUsuarioModField;
        
        private string sLogHoraModField;
        
        private string sLogFechaModField;
        
        private int intNum_SecuencialField;
        
        private string sCausalRehabilitacionField;
        
        private string sDscMotivoField;
        
        private string sNroOperacionField;
        
        /// <remarks/>
        public string SCodNumeroTicket {
            get {
                return this.sCodNumeroTicketField;
            }
            set {
                this.sCodNumeroTicketField = value;
            }
        }
        
        /// <remarks/>
        public string STipEstado {
            get {
                return this.sTipEstadoField;
            }
            set {
                this.sTipEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string SDscTicketEstado {
            get {
                return this.sDscTicketEstadoField;
            }
            set {
                this.sDscTicketEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string SCodEquipoMod {
            get {
                return this.sCodEquipoModField;
            }
            set {
                this.sCodEquipoModField = value;
            }
        }
        
        /// <remarks/>
        public string SDscNumVuelo {
            get {
                return this.sDscNumVueloField;
            }
            set {
                this.sDscNumVueloField = value;
            }
        }
        
        /// <remarks/>
        public string SLogUsuarioMod {
            get {
                return this.sLogUsuarioModField;
            }
            set {
                this.sLogUsuarioModField = value;
            }
        }
        
        /// <remarks/>
        public string SLogHoraMod {
            get {
                return this.sLogHoraModField;
            }
            set {
                this.sLogHoraModField = value;
            }
        }
        
        /// <remarks/>
        public string SLogFechaMod {
            get {
                return this.sLogFechaModField;
            }
            set {
                this.sLogFechaModField = value;
            }
        }
        
        /// <remarks/>
        public int IntNum_Secuencial {
            get {
                return this.intNum_SecuencialField;
            }
            set {
                this.intNum_SecuencialField = value;
            }
        }
        
        /// <remarks/>
        public string SCausalRehabilitacion {
            get {
                return this.sCausalRehabilitacionField;
            }
            set {
                this.sCausalRehabilitacionField = value;
            }
        }
        
        /// <remarks/>
        public string SDscMotivo {
            get {
                return this.sDscMotivoField;
            }
            set {
                this.sDscMotivoField = value;
            }
        }
        
        /// <remarks/>
        public string SNroOperacion {
            get {
                return this.sNroOperacionField;
            }
            set {
                this.sNroOperacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BoardingBcbpEstHist {
        
        private int iNumSecuencialField;
        
        private int iNumSecuencialBoardingField;
        
        private string sTipEstadoField;
        
        private string sDscBoardingEstadoField;
        
        private string sCodEquipoModField;
        
        private string sDscNumVueloField;
        
        private string sLogUsuarioModField;
        
        private string sLogFechaModField;
        
        private string sLogHoraModField;
        
        private string sCausalRehabilitacionField;
        
        private string sListaBcbPsField;
        
        private string sEstadoAsocField;
        
        private string sCompaniaAsocField;
        
        private string sFechaVueloAsocField;
        
        private string sNroVueloAsocField;
        
        private string sNroAsientoAsocField;
        
        private string sPasajeroAsocField;
        
        private string lst_BloqueadosField;
        
        private string sListaOperBcbpField;
        
        private string sFechaRehabField;
        
        private string sDesCompaniaField;
        
        private string sDesMotivoField;
        
        /// <remarks/>
        public int INumSecuencial {
            get {
                return this.iNumSecuencialField;
            }
            set {
                this.iNumSecuencialField = value;
            }
        }
        
        /// <remarks/>
        public int INumSecuencialBoarding {
            get {
                return this.iNumSecuencialBoardingField;
            }
            set {
                this.iNumSecuencialBoardingField = value;
            }
        }
        
        /// <remarks/>
        public string STipEstado {
            get {
                return this.sTipEstadoField;
            }
            set {
                this.sTipEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string SDscBoardingEstado {
            get {
                return this.sDscBoardingEstadoField;
            }
            set {
                this.sDscBoardingEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string SCodEquipoMod {
            get {
                return this.sCodEquipoModField;
            }
            set {
                this.sCodEquipoModField = value;
            }
        }
        
        /// <remarks/>
        public string SDscNumVuelo {
            get {
                return this.sDscNumVueloField;
            }
            set {
                this.sDscNumVueloField = value;
            }
        }
        
        /// <remarks/>
        public string SLogUsuarioMod {
            get {
                return this.sLogUsuarioModField;
            }
            set {
                this.sLogUsuarioModField = value;
            }
        }
        
        /// <remarks/>
        public string SLogFechaMod {
            get {
                return this.sLogFechaModField;
            }
            set {
                this.sLogFechaModField = value;
            }
        }
        
        /// <remarks/>
        public string SLogHoraMod {
            get {
                return this.sLogHoraModField;
            }
            set {
                this.sLogHoraModField = value;
            }
        }
        
        /// <remarks/>
        public string SCausalRehabilitacion {
            get {
                return this.sCausalRehabilitacionField;
            }
            set {
                this.sCausalRehabilitacionField = value;
            }
        }
        
        /// <remarks/>
        public string SListaBcbPs {
            get {
                return this.sListaBcbPsField;
            }
            set {
                this.sListaBcbPsField = value;
            }
        }
        
        /// <remarks/>
        public string SEstadoAsoc {
            get {
                return this.sEstadoAsocField;
            }
            set {
                this.sEstadoAsocField = value;
            }
        }
        
        /// <remarks/>
        public string SCompaniaAsoc {
            get {
                return this.sCompaniaAsocField;
            }
            set {
                this.sCompaniaAsocField = value;
            }
        }
        
        /// <remarks/>
        public string SFechaVueloAsoc {
            get {
                return this.sFechaVueloAsocField;
            }
            set {
                this.sFechaVueloAsocField = value;
            }
        }
        
        /// <remarks/>
        public string SNroVueloAsoc {
            get {
                return this.sNroVueloAsocField;
            }
            set {
                this.sNroVueloAsocField = value;
            }
        }
        
        /// <remarks/>
        public string SNroAsientoAsoc {
            get {
                return this.sNroAsientoAsocField;
            }
            set {
                this.sNroAsientoAsocField = value;
            }
        }
        
        /// <remarks/>
        public string SPasajeroAsoc {
            get {
                return this.sPasajeroAsocField;
            }
            set {
                this.sPasajeroAsocField = value;
            }
        }
        
        /// <remarks/>
        public string Lst_Bloqueados {
            get {
                return this.lst_BloqueadosField;
            }
            set {
                this.lst_BloqueadosField = value;
            }
        }
        
        /// <remarks/>
        public string SListaOperBcbp {
            get {
                return this.sListaOperBcbpField;
            }
            set {
                this.sListaOperBcbpField = value;
            }
        }
        
        /// <remarks/>
        public string SFechaRehab {
            get {
                return this.sFechaRehabField;
            }
            set {
                this.sFechaRehabField = value;
            }
        }
        
        /// <remarks/>
        public string SDesCompania {
            get {
                return this.sDesCompaniaField;
            }
            set {
                this.sDesCompaniaField = value;
            }
        }
        
        /// <remarks/>
        public string SDesMotivo {
            get {
                return this.sDesMotivoField;
            }
            set {
                this.sDesMotivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ConsultarRepresXRehabilitacionYCiaCompletedEventHandler(object sender, ConsultarRepresXRehabilitacionYCiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarRepresXRehabilitacionYCiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarRepresXRehabilitacionYCiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void registrarRehabilitacionTicketCompletedEventHandler(object sender, registrarRehabilitacionTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarRehabilitacionTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarRehabilitacionTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TicketEstHist objTicketEstHist {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TicketEstHist)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void consultarVuelosTicketPorCiaFechaCompletedEventHandler(object sender, consultarVuelosTicketPorCiaFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarVuelosTicketPorCiaFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarVuelosTicketPorCiaFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void consultarTicketsPorVueloCompletedEventHandler(object sender, consultarTicketsPorVueloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarTicketsPorVueloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarTicketsPorVueloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void consultarVuelosBCBPPorCiaFechaCompletedEventHandler(object sender, consultarVuelosBCBPPorCiaFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarVuelosBCBPPorCiaFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarVuelosBCBPPorCiaFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void registrarRehabilitacionBCBPCompletedEventHandler(object sender, registrarRehabilitacionBCBPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarRehabilitacionBCBPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarRehabilitacionBCBPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public BoardingBcbpEstHist boardingBcbpEstHist {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BoardingBcbpEstHist)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void registrarRehabilitacionBCBPAmpliacionCompletedEventHandler(object sender, registrarRehabilitacionBCBPAmpliacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarRehabilitacionBCBPAmpliacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarRehabilitacionBCBPAmpliacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public BoardingBcbpEstHist boardingBcbpEstHist {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BoardingBcbpEstHist)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void listarCompania_xCodigoEspecialCompletedEventHandler(object sender, listarCompania_xCodigoEspecialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarCompania_xCodigoEspecialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarCompania_xCodigoEspecialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void obteneterBoardingsByRangoFechasCompletedEventHandler(object sender, obteneterBoardingsByRangoFechasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obteneterBoardingsByRangoFechasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obteneterBoardingsByRangoFechasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591